/*
 * FreeRTOS Kernel V10.3.1
 * Copyright (C) 2020 Amazon.com, Inc. or its affiliates.  All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * http://www.FreeRTOS.org
 * http://aws.amazon.com/freertos
 *
 * 1 tab == 4 spaces!
 */

/* FreeRTOS includes. */
#include "FreeRTOS.h"
#include "task.h"

/* Platform includes. */
#include "platform.h"
#include "sys_driver.h"

#if CONFIG_SYSTEM_CTRL
#include <modules/pm.h>
#endif

#if CONFIG_AON_RTC
#include <driver/aon_rtc.h>
#include <driver/aon_rtc_types.h>
#endif

#include <components/log.h>

#define TAG  "os"

/* Macros for save/restore global interrupt (mstatus.mie) */
#define prvMIE_SAVE()       prvMieSave()
#define prvMIE_RESTORE( x ) prvMieRestore( x )

/* Macros to access high and low part of 64-bit mtime registers in RV32 */
#if __riscv_xlen == 32
	#define prvREG64_HI(reg_addr) ( ( (volatile uint32_t *)( reg_addr ) )[1] )
	#define prvREG64_LO(reg_addr) ( ( (volatile uint32_t *)( reg_addr ) )[0] )
#endif

/*-----------------------------------------------------------*/

extern uint64_t ullNextTime;
extern const size_t uxTimerIncrementsForOneTick;
extern volatile uint64_t * pullMachineTimerCompareRegister;
extern uint32_t pm_debug_mode();

#if( configUSE_TICKLESS_IDLE != 0 )
	/* Flag set from the timer interrupt to allow the sleep processing to know if
	sleep mode was exited because of a tick interrupt, or an interrupt
	generated by something else. */
	volatile BaseType_t xTickFlag = 0;
#endif /* configUSE_TICKLESS_IDLE */

#if CONFIG_AON_RTC
	#define RTC_WAKEUP_TIMER       "rtc_wk"
	#define OS_MS_PER_TICK          (1000/configTICK_RATE_HZ)
	#define RTC_TICKS_PER_OS_TICK   (RTC_TICKS_PER_1MS*OS_MS_PER_TICK)
	#define OS_SLEEP_MIN_TICKS      (3)
	#define OS_SLEEP_MAX_TICKS      (60*60*1000/OS_MS_PER_TICK)   //60min

	static uint64_t base_aon_time = 0;
	static uint32_t base_os_time = 0;
#endif


__maybe_unused void rtos_init_base_time(void) {
#if CONFIG_AON_RTC
	base_aon_time = bk_aon_rtc_get_current_tick(AON_RTC_ID_1);
	base_os_time = rtos_get_time();
	BK_LOGI(TAG, "os time(%dms),rtc time(%dms).\r\n", base_os_time,
		(uint32_t)base_aon_time/RTC_TICKS_PER_1MS);
	BK_LOGI(TAG, "base aon rtc time: %d:%d\r\n", (uint32_t)(base_aon_time >> 32),
		(uint32_t)(base_aon_time & 0xFFFFFFFF));
#endif
}

uint32_t rtos_get_time_diff(void) {
#if CONFIG_AON_RTC
	uint64_t cur_aon_time = bk_aon_rtc_get_current_tick(AON_RTC_ID_1);
	uint64_t cur_os_time = (uint64_t)rtos_get_time(); //ms
	uint64_t diff_time = (cur_aon_time - base_aon_time)/RTC_TICKS_PER_1MS; //ms



	if (diff_time + base_os_time < cur_os_time) {
		return 0;
	}

	return (uint32_t)(diff_time - cur_os_time + base_os_time) / OS_MS_PER_TICK; // tick
#else
	return 0;
#endif
}

/*-----------------------------------------------------------*/

#if( configUSE_TICKLESS_IDLE != 0 )
	/* prvReadMtime(): Read machine timer register.
	Note: Always use this API to access mtime */
	static portFORCE_INLINE uint64_t prvReadMtime( void )
	{
		volatile uint64_t * const pullMtimeRegister = ( volatile uint64_t * const ) ( configMTIME_BASE_ADDRESS );

		#if __riscv_xlen == 32
			uint32_t ulCurrentTimeHigh, ulCurrentTimeLow;
			do
			{
				ulCurrentTimeHigh = prvREG64_HI( pullMtimeRegister );
				ulCurrentTimeLow = prvREG64_LO( pullMtimeRegister );
			} while ( ulCurrentTimeHigh != prvREG64_HI( pullMtimeRegister ) );

			return ( ( ( uint64_t ) ulCurrentTimeHigh ) << 32 ) | ulCurrentTimeLow;
		#else
			return *pullMtimeRegister;
		#endif
	}
	/*-----------------------------------------------------------*/

	/* prvWriteMtimecmp(ullNewMtimecmp): Write machine timer compare register.
	Note: Use this API to access register if timer interrupt is enabled. */
	static portFORCE_INLINE void prvWriteMtimecmp( uint64_t ullNewMtimecmp )
	{
		if( pullMachineTimerCompareRegister == NULL )
			return;

		#if __riscv_xlen == 32
			/* To avoid triggering spurious interrupts when writting to mtimecmp,
			keeping the high part to the maximum value in the writing progress.

			We assume mtime overflow doesn't occur, because 64-bit mtime overflow
			period is longer than 500 years for the CPUs whose clock rate is lower
			than 1GHz. */

			prvREG64_HI( pullMachineTimerCompareRegister ) = UINT32_MAX;
			prvREG64_LO( pullMachineTimerCompareRegister ) = ullNewMtimecmp & 0xFFFFFFFF;
			prvREG64_HI( pullMachineTimerCompareRegister ) = ( ullNewMtimecmp >> 32 ) & 0xFFFFFFFF;
		#else
			*pullMachineTimerCompareRegister = ullNewMtimecmp;
		#endif
	}
	/*-----------------------------------------------------------*/

	static portFORCE_INLINE UBaseType_t prvMieSave()
	{
	UBaseType_t uxSavedStatusValue;

		__asm volatile( "csrrc %0, mstatus, 0x8":"=r"( uxSavedStatusValue ) );
		return uxSavedStatusValue;
	}
	/*-----------------------------------------------------------*/

	static portFORCE_INLINE void prvMieRestore( UBaseType_t uxSavedStatusValue )
	{
		__asm volatile( "csrw mstatus, %0"::"r"( uxSavedStatusValue ) );
	}
	/*-----------------------------------------------------------*/

	/* Stop mtime interrupt by setting timer compare register to maximum value.
	The return value is previous value of timer compare register.
	Again, like prvWriteMtimecmp(), We assume mtime overflow doesn't occur. */
	static portFORCE_INLINE uint64_t prvStopMtimeIrq( void )
	{
	uint64_t ullSavedMtimecmp;
	UBaseType_t uxSavedStatus;

		uxSavedStatus = prvMIE_SAVE();
		{
			ullSavedMtimecmp = *pullMachineTimerCompareRegister;
			*pullMachineTimerCompareRegister = UINT64_MAX;
		}
		prvMIE_RESTORE( uxSavedStatus );
		return ullSavedMtimecmp;
	}
	/*-----------------------------------------------------------*/


	/*-----------------------------------------------------------*/

	void FreeRTOS_tickless_handler( void )
	{
		/* Tick ISR has occured */
		xTickFlag = 1;

		/*
		 * Handle the corner case for system very busy on handling IRQs.
		 *
		 * If Timer ISR is pending after (ullWakeUpTime + 1) Ticks, Timer ISR
		 * will increase 2 Ticks in tickless idle mode so that it is possible to
		 * trigger assertion in vTaskStepTick() and it can cause Timer ISR stop
		 * until very long future if assertion is disabled.
		 *
		 * Fix assertion / timer ISR stop issue but losing tick value can't be
		 * avoided.
		 */
		uint64_t ullCurrentTime = prvReadMtime();
		if( ullCurrentTime > ullNextTime ){
			ullNextTime = ullCurrentTime + uxTimerIncrementsForOneTick;
		}
	}
#endif /* configUSE_TICKLESS_IDLE */

#if (configUSE_TICKLESS_IDLE == 1)
__attribute__((section(".itcm_sec_code")))	void vPortSuppressTicksAndSleep( TickType_t xExpectedIdleTime )
	{
	/* The maximum number of tick periods that can be suppressed is limited by
	the resolution of the Timer */
	#define portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS ( (1ULL << 60) / uxTimerIncrementsForOneTick )

	/* Unit: cycle */
	uint64_t ullNextTickTime, ullWakeUpTime, ullCurrentTime;

	/* Unit: tick */
	TickType_t xCompleteTickPeriods, xTickPeriodsBeforeWakeup, xModifiableIdleTime;

		/* To avoid integer overflow when assigning maximum tick periods
		to xExpectedIdleTime, check portMAX_DELAY first.
		p.s. xExpectedIdleTime is always lower than portMAX_DELAY */
		if( portMAX_DELAY > portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS )
		{
			/* if portMAX_DELAY > portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS, then the
			size of TickType_t is larger than or equal to maximum tick periods */
			if( xExpectedIdleTime > portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS )
			{
				xExpectedIdleTime = (TickType_t) portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS;
			}
		}

		/* Stop mtime interrupt */
		ullNextTickTime = prvStopMtimeIrq();

		/* Calculate the mtimecmp value to wait xExpectedIdleTime tick periods.
		Wakeup time is at ( xExpectedIdleTime - 1 ) ticks after next tick. */
		ullWakeUpTime = ullNextTickTime + ( ( xExpectedIdleTime - 1 ) * (uint64_t)uxTimerIncrementsForOneTick );

		portDISABLE_INTERRUPTS();
		if( eTaskConfirmSleepModeStatus() == eAbortSleep )
		{

			/* Set reload value and restart timer */
			prvWriteMtimecmp( ullNextTickTime );

			/* Re-enable interrupts. */
			portENABLE_INTERRUPTS();
		}
		else
		{
			/* The tick flag is set to false before sleeping. If it is true when
			sleep mode is exited then sleep mode was probably exited because the
			tick was suppressed for the entire xExpectedIdleTime period. */
			xTickFlag = 0;

			/* Set wakeup time and restart timer. Also prepare next mtimecmp value
			for Timer ISR. */
			prvWriteMtimecmp( ullWakeUpTime );
			ullNextTime = ullWakeUpTime + uxTimerIncrementsForOneTick;

			/* Sleep until something happens.  configPRE_SLEEP_PROCESSING() can
			set its parameter to 0 to indicate that its implementation contains
			its own wait for interrupt or wait for event instruction, and so wfi
			should not be executed again.  However, the original expected idle
			time variable must remain unmodified, so a copy is taken. */
			xModifiableIdleTime = xExpectedIdleTime;
			configPRE_SLEEP_PROCESSING( xModifiableIdleTime );
			if( xModifiableIdleTime > 0 )
			{
				__asm volatile( "wfi" );
			}
			configPOST_SLEEP_PROCESSING( xExpectedIdleTime );

			/* Re-enable interrupts to allow the interrupt that brought the MCU
			out of sleep mode to execute immediately. */
			portENABLE_INTERRUPTS();

			/* Disable interrupts again to avoid timer ISR runs after checking
			xTickFlag. */
			portDISABLE_INTERRUPTS();

			if( xTickFlag == 1 )
			{
				/* As the pending tick will be processed as soon as this
				function exits, the tick value maintained by the tick is stepped
				forward by one less than the time spent waiting. */
				xCompleteTickPeriods = xExpectedIdleTime - 1;

				/* Note: mtimecmp is correct in this condition, so we doesn't
				need to access it */
			}
			else
			{
				ullCurrentTime = prvReadMtime();

				if( ullCurrentTime >= ullWakeUpTime )
				{
					/* Tick interrupt is pending because it occurs after
					disabling MIE. The tick value is stepped forward by
					the time spent waiting. */
					xCompleteTickPeriods = xExpectedIdleTime - 1;
				}
				else
				{
					/* Something other than the tick interrupt ended the sleep.
					Work out how long the sleep lasted rounded to complete tick
					periods. */

					/* Round up the tick period before wakeup to the Tick unit */
					xTickPeriodsBeforeWakeup = ( ullWakeUpTime - ullCurrentTime - 1 ) / uxTimerIncrementsForOneTick + 1;
					xCompleteTickPeriods = xExpectedIdleTime - xTickPeriodsBeforeWakeup;
				}

				ullNextTime = ullNextTickTime + ( ( ( uint64_t ) xCompleteTickPeriods ) * uxTimerIncrementsForOneTick );
				prvWriteMtimecmp( ullNextTime );

				/* Prepare next mtimecmp value for Timer ISR. */
			    ullNextTime += ( uint64_t ) uxTimerIncrementsForOneTick;
			}

			vTaskStepTick( xCompleteTickPeriods );

			/* Exit with interrpts enabled. */
			portENABLE_INTERRUPTS();
		}
	}
#endif //if (configUSE_TICKLESS_IDLE == 1)
/*-----------------------------------------------------------*/

#if (configUSE_TICKLESS_IDLE == 2)

// volatile uint32_t timer_state = 0;
// static void cli_pm_rtc_callback(aon_rtc_id_t id, uint8_t *name_p, void *param) {
// 	timer_state = 1;
// }

// 	static void vSetWakeUpTimer(TickType_t xWakeUpTime)	{
// #if CONFIG_AON_RTC
// 		uint32_t period_tick = xWakeUpTime*RTC_TICKS_PER_OS_TICK;
// 		alarm_info_t low_valtage_alarm = {
// 								RTC_WAKEUP_TIMER,
// 								period_tick,
// 								1,
// 								NULL,
// 								NULL
// 								};

// 		bk_alarm_register(AON_RTC_ID_1, &low_valtage_alarm);
// 		// timer_state = 0;
// #endif
// 	}

// 	static void vCancelWakeUpTimer() {
// #if CONFIG_AON_RTC
// 		uint8_t name[ALARM_NAME_MAX_LEN+1] = {RTC_WAKEUP_TIMER};
// 		bk_alarm_unregister(AON_RTC_ID_1, name);
// #endif
// 	}


__attribute__((section(".itcm_sec_code")))	void vPortSuppressTicksAndSleep( TickType_t xExpectedIdleTime )
	{
		/* The maximum number of tick periods that can be suppressed is limited by
		the resolution of the Timer */
	#if CONFIG_AON_RTC
		#define portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS ( (1ULL << 32) / RTC_TICKS_PER_OS_TICK )
		#define portULL_MINIMUM_POSSIBLE_SUPPRESSED_TICKS ( 2 )

	#endif
		UBaseType_t uxSavedInterruptState;

		TickType_t  xSleepTicks;

#if CONFIG_SYSTEM_CTRL
		TickType_t xModifiableIdleTime;
#endif

		/* To avoid integer overflow when assigning maximum tick periods
		to xExpectedIdleTime, check portMAX_DELAY first.
		p.s. xExpectedIdleTime is always lower than portMAX_DELAY */
		{
			/* if portMAX_DELAY > portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS, then the
			size of TickType_t is larger than or equal to maximum tick periods */
			if( xExpectedIdleTime > portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS )
			{
				xExpectedIdleTime = (TickType_t) portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS;
			}
		}

		uxSavedInterruptState = portSET_INTERRUPT_MASK_FROM_ISR();

		if( eTaskConfirmSleepModeStatus() == eAbortSleep )
		{
			/* Re-enable interrupts. */
			portCLEAR_INTERRUPT_MASK_FROM_ISR(uxSavedInterruptState);
		}
		else
		{
			/* The tick flag is set to false before sleeping. If it is true when
			sleep mode is exited then sleep mode was probably exited because the
			tick was suppressed for the entire xExpectedIdleTime period. */
			// xTickFlag = 0;

			/* Set wakeup timer. */
			// vSetWakeUpTimer(xWakeUpTimes);

#if CONFIG_SYSTEM_CTRL
			/* Sleep until something happens.  configPRE_SLEEP_PROCESSING() can
			set its parameter to 0 to indicate that its implementation contains
			its own wait for interrupt or wait for event instruction, and so wfi
			should not be executed again.  However, the original expected idle
			time variable must remain unmodified, so a copy is taken. */
			xModifiableIdleTime = xExpectedIdleTime;
			bk_pm_suppress_ticks_and_sleep(xModifiableIdleTime);
#else
			__asm volatile( "wfi" );
#endif

#if CONFIG_AON_RTC
			xSleepTicks = rtos_get_time_diff();

			if(xSleepTicks != 0 && xSleepTicks != 1) {
				if(pm_debug_mode()&0x8) {
                	BK_LOGI(TAG, "expect%dsleep%dms.\r\n", xExpectedIdleTime<<1, xSleepTicks<<1);
       			}

				vTaskStepTick(xSleepTicks - 1);
			}
#endif
			/* Exit with interrpts enabled. */
			portCLEAR_INTERRUPT_MASK_FROM_ISR(uxSavedInterruptState);
		}
	}

#endif // (configUSE_TICKLESS_IDLE == 2)

#if 0
/* We don't need these functions anymore, because it is handling in generic code. */
/*
 * Create implementation of vPortSetupTimerInterrupt() if the CLINT is not
 * available, but make sure the configCLINT_BASE_ADDRESS constant is still
 * defined.
 */
void vPortSetupTimerInterrupt( void )
{
	ullNextTime = prvReadMtime();
	ullNextTime += ( uint64_t ) uxTimerIncrementsForOneTick;
	*pullMachineTimerCompareRegister = ullNextTime;

	/* Prepare the time to use after the next tick interrupt. */
	ullNextTime += ( uint64_t ) uxTimerIncrementsForOneTick;

	/* Enable mtime interrupt */
	__asm volatile( "csrs mie,%0" :: "r"(0x80) );
}
/*-----------------------------------------------------------*/

void FreeRTOS_tick_handler( void )
{
	/* Handle tickless idle before Timer ISR updates mtimecmp. */
	#if( configUSE_TICKLESS_IDLE == 1 )
		FreeRTOS_tickless_handler();
	#endif /* configUSE_TICKLESS_IDLE */

	/* Update the mtimer compare match value. */
	prvWriteMtimecmp( ullNextTime );

	/* Add ullNextTime to the timer increments for one tick. */
	ullNextTime += ( uint64_t ) uxTimerIncrementsForOneTick;

	if( xTaskIncrementTick() != pdFALSE )
	{
		vTaskSwitchContext();
	}
}
/*-----------------------------------------------------------*/
#endif
