// Copyright 2020-2021 Beken 
// 
// Licensed under the Apache License, Version 2.0 (the "License");           
// you may not use this file except in compliance with the License.            
// You may obtain a copy of the License at                                     
//                                                                             
//     http://www.apache.org/licenses/LICENSE-2.0                              
//                                                                             
// Unless required by applicable law or agreed to in writing, software         
// distributed under the License is distributed on an "AS IS" BASIS,         
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    
// See the License for the specific language governing permissions and         
// limitations under the License.                                              

/***********************************************************************************************************************************
* This file is generated from BK7256_ADDR Mapping_20211224_format_change_highlight_20220113_update.xlsm automatically                                
* Modify it manually is not recommended                                       
* CHIP ID:BK7256,GENARATE TIME:2022-04-02 18:47:01                                                 
************************************************************************************************************************************/

#pragma once 

#ifdef __cplusplus
extern "C" {
#endif

#define SDIO_LL_REG_BASE      (SOC_SDIO_REG_BASE) //REG_BASE:0x448B0000
	
/* REG_0x00 */
#define SDIO_REG0X0_ADDR  (SDIO_LL_REG_BASE  + 0x0*4) //REG ADDR :0x448b0000
#define SDIO_REG0X0_SD_CMD_START_POS (0) 
#define SDIO_REG0X0_SD_CMD_START_MASK (0x1) 
	
#define SDIO_REG0X0_SD_CMD_RSP_POS (1) 
#define SDIO_REG0X0_SD_CMD_RSP_MASK (0x1) 
	
#define SDIO_REG0X0_SD_CMD_LONG_POS (2) 
#define SDIO_REG0X0_SD_CMD_LONG_MASK (0x1) 
	
#define SDIO_REG0X0_SD_CMD_CRC_CHECK_POS (3) 
#define SDIO_REG0X0_SD_CMD_CRC_CHECK_MASK (0x1) 
	
#define SDIO_REG0X0_CMD_INDEX_POS (4) 
#define SDIO_REG0X0_CMD_INDEX_MASK (0x3F) 
	
#define SDIO_REG0X0_RESERVED0_POS (10) 
#define SDIO_REG0X0_RESERVED0_MASK (0x3FFFFF)

/* REG_0x01 */
#define SDIO_REG0X1_ADDR  (SDIO_LL_REG_BASE  + 0x1*4) //REG ADDR :0x448b0004
#define SDIO_REG0X1_CMD_ARGUMENT_POS (0) 
#define SDIO_REG0X1_CMD_ARGUMENT_MASK (0xFFFFFFFF) 
	
/* REG_0x02 */
#define SDIO_REG0X2_ADDR  (SDIO_LL_REG_BASE  + 0x2*4) //REG ADDR :0x448b0008
#define SDIO_REG0X2_SD_CMD_TIMER_POS (0) 
#define SDIO_REG0X2_SD_CMD_TIMER_MASK (0xFFFFFFFF) 
	
/* REG_0x03 */
#define SDIO_REG0X3_ADDR  (SDIO_LL_REG_BASE  + 0x3*4) //REG ADDR :0x448b000c
#define SDIO_REG0X3_SD_DATA_EN_POS (0) 
#define SDIO_REG0X3_SD_DATA_EN_MASK (0x1) 
	
#define SDIO_REG0X3_SD_DATA_STOP_EN_POS (1) 
#define SDIO_REG0X3_SD_DATA_STOP_EN_MASK (0x1) 
	
#define SDIO_REG0X3_SD_DATA_BUS_POS (2) 
#define SDIO_REG0X3_SD_DATA_BUS_MASK (0x1) 
	
#define SDIO_REG0X3_SD_DATA_MUL_BLK_POS (3) 
#define SDIO_REG0X3_SD_DATA_MUL_BLK_MASK (0x1) 
	
#define SDIO_REG0X3_SD_DATA_BLK_SIZE_POS (4) 
#define SDIO_REG0X3_SD_DATA_BLK_SIZE_MASK (0xFFF) 
	
#define SDIO_REG0X3_SD_START_WR_EN_POS (16) 
#define SDIO_REG0X3_SD_START_WR_EN_MASK (0x1) 
	
#define SDIO_REG0X3_SD_BYTE_SEL_POS (17) 
#define SDIO_REG0X3_SD_BYTE_SEL_MASK (0x1) 
	
#define SDIO_REG0X3_RESERVED0_POS (18) 
#define SDIO_REG0X3_RESERVED0_MASK (0x3FFF) 
	
/* REG_0x04 */
#define SDIO_REG0X4_ADDR  (SDIO_LL_REG_BASE  + 0x4*4) //REG ADDR :0x448b0010
#define SDIO_REG0X4_SD_DATA_TIMER_POS (0) 
#define SDIO_REG0X4_SD_DATA_TIMER_MASK (0xFFFFFFFF) 
	
/* REG_0x05 */
#define SDIO_REG0X5_ADDR  (SDIO_LL_REG_BASE  + 0x5*4) //REG ADDR :0x448b0014
#define SDIO_REG0X5_SD_RSP_AGUMENT_0_POS (0) 
#define SDIO_REG0X5_SD_RSP_AGUMENT_0_MASK (0xFFFFFFFF) 
	
/* REG_0x06 */
#define SDIO_REG0X6_ADDR  (SDIO_LL_REG_BASE  + 0x6*4) //REG ADDR :0x448b0018
#define SDIO_REG0X6_SD_RSP_AGUMENT_1_POS (0) 
#define SDIO_REG0X6_SD_RSP_AGUMENT_1_MASK (0xFFFFFFFF) 

/* REG_0x07 */
#define SDIO_REG0X7_ADDR  (SDIO_LL_REG_BASE  + 0x7*4) //REG ADDR :0x448b001c
#define SDIO_REG0X7_SD_RSP_AGUMENT_2_POS (0) 
#define SDIO_REG0X7_SD_RSP_AGUMENT_2_MASK (0xFFFFFFFF) 
	
/* REG_0x08 */
#define SDIO_REG0X8_ADDR  (SDIO_LL_REG_BASE  + 0x8*4) //REG ADDR :0x448b0020
#define SDIO_REG0X8_SD_RSP_AGUMENT_3_POS (0) 
#define SDIO_REG0X8_SD_RSP_AGUMENT_3_MASK (0xFFFFFFFF) 
	
	
/* REG_0x09 */
#define SDIO_REG0X9_ADDR  (SDIO_LL_REG_BASE  + 0x9*4) //REG ADDR :0x448b0024
#define SDIO_REG0X9_SD_CMD_SEND_NORSP_END_INT_POS (0) 
#define SDIO_REG0X9_SD_CMD_SEND_NORSP_END_INT_MASK (0x1) 
	
#define SDIO_REG0X9_SD_CMD_SEND_RSP_END_INT_POS (1) 
#define SDIO_REG0X9_SD_CMD_SEND_RSP_END_INT_MASK (0x1) 
	
#define SDIO_REG0X9_SD_CMD_SEND_RSP_TIMEOUT_INT_POS (2) 
#define SDIO_REG0X9_SD_CMD_SEND_RSP_TIMEOUT_INT_MASK (0x1) 
	
#define SDIO_REG0X9_SD_DATA_REC_END_INT_POS (3) 
#define SDIO_REG0X9_SD_DATA_REC_END_INT_MASK (0x1) 
	
#define SDIO_REG0X9_SD_DATA_WR_END_INT_POS (4) 
#define SDIO_REG0X9_SD_DATA_WR_END_INT_MASK (0x1) 
	
#define SDIO_REG0X9_SD_DATA_TIME_OUT_INT_POS (5) 
#define SDIO_REG0X9_SD_DATA_TIME_OUT_INT_MASK (0x1) 
	
#define SDIO_REG0X9_RX_FIFO_NEED_READ_POS (6) 
#define SDIO_REG0X9_RX_FIFO_NEED_READ_MASK (0x1) 
	
#define SDIO_REG0X9_TX_FIFO_NEED_WRITE_POS (7) 
#define SDIO_REG0X9_TX_FIFO_NEED_WRITE_MASK (0x1) 
	
#define SDIO_REG0X9_RX_OV_POS (8) 
#define SDIO_REG0X9_RX_OV_MASK (0x1) 
	
#define SDIO_REG0X9_TX_FIFO_EMPT_POS (9) 
#define SDIO_REG0X9_TX_FIFO_EMPT_MASK (0x1) 
	
#define SDIO_REG0X9_SD_RSP_CMD_CRC_OK_POS (10) 
#define SDIO_REG0X9_SD_RSP_CMD_CRC_OK_MASK (0x1) 
	
#define SDIO_REG0X9_SD_RSP_CMD_CRC_FAIL_POS (11) 
#define SDIO_REG0X9_SD_RSP_CMD_CRC_FAIL_MASK (0x1) 
	
#define SDIO_REG0X9_SD_DATA_CRC_OK_POS (12) 
#define SDIO_REG0X9_SD_DATA_CRC_OK_MASK (0x1) 
	
#define SDIO_REG0X9_SD_DATA_CRC_FAIL_POS (13) 
#define SDIO_REG0X9_SD_DATA_CRC_FAIL_MASK (0x1) 
	
#define SDIO_REG0X9_SD_RSP_INDEX_POS (14) 
#define SDIO_REG0X9_SD_RSP_INDEX_MASK (0x3F) 
	
#define SDIO_REG0X9_WR_STATUS_POS (20) 
#define SDIO_REG0X9_WR_STATUS_MASK (0x7) 
	
#define SDIO_REG0X9_DATA_BUSY_POS (23) 
#define SDIO_REG0X9_DATA_BUSY_MASK (0x1) 
	
#define SDIO_REG0X9_CMD_S_RES_END_INT_POS (24) 
#define SDIO_REG0X9_CMD_S_RES_END_INT_MASK (0x1) 
	
#define SDIO_REG0X9_DAT_S_WR_WAI_INT_POS (25) 
#define SDIO_REG0X9_DAT_S_WR_WAI_INT_MASK (0x1) 
	
#define SDIO_REG0X9_DAT_S_RD_BUS_INT_POS (26) 
#define SDIO_REG0X9_DAT_S_RD_BUS_INT_MASK (0x1) 
	
#define SDIO_REG0X9_RESERVED0_POS (27) 
#define SDIO_REG0X9_RESERVED0_MASK (0x1F) 
	
/* REG_0x0A */
#define SDIO_REG0XA_ADDR  (SDIO_LL_REG_BASE  + 0xA*4) //REG ADDR :0x448b0028
#define SDIO_REG0XA_SD_CMD_SEND_NORSP_END_MASK_POS (0) 
#define SDIO_REG0XA_SD_CMD_SEND_NORSP_END_MASK_MASK (0x1) 
	
#define SDIO_REG0XA_SD_CMD_SEND_RSP_END_MASK_POS (1) 
#define SDIO_REG0XA_SD_CMD_SEND_RSP_END_MASK_MASK (0x1) 
	
#define SDIO_REG0XA_SD_CMD_SEND_RSP_TIMEOUT_MASK_POS (2) 
#define SDIO_REG0XA_SD_CMD_SEND_RSP_TIMEOUT_MASK_MASK (0x1) 
	
#define SDIO_REG0XA_SD_DATA_REC_END_MASK_POS (3) 
#define SDIO_REG0XA_SD_DATA_REC_END_MASK_MASK (0x1) 
	
#define SDIO_REG0XA_SD_DATA_WR_END_MASK_POS (4) 
#define SDIO_REG0XA_SD_DATA_WR_END_MASK_MASK (0x1) 
	
#define SDIO_REG0XA_SD_DATA_TIME_OUT_MASK_POS (5) 
#define SDIO_REG0XA_SD_DATA_TIME_OUT_MASK_MASK (0x1) 
	
#define SDIO_REG0XA_RX_FIFO_NEED_READ_MASK_POS (6) 
#define SDIO_REG0XA_RX_FIFO_NEED_READ_MASK_MASK (0x1) 
	
#define SDIO_REG0XA_TX_FIFO_NEED_WRITE_MASK_POS (7) 
#define SDIO_REG0XA_TX_FIFO_NEED_WRITE_MASK_MASK (0x1) 
	
#define SDIO_REG0XA_RX_OV_MASK_POS (8) 
#define SDIO_REG0XA_RX_OV_MASK_MASK (0x1) 
	
#define SDIO_REG0XA_TX_FIFO_EMPT_MASK_POS (9) 
#define SDIO_REG0XA_TX_FIFO_EMPT_MASK_MASK (0x1) 
	
#define SDIO_REG0XA_CMD_S_RES_END_INT_MASK_POS (10) 
#define SDIO_REG0XA_CMD_S_RES_END_INT_MASK_MASK (0x1) 
	
#define SDIO_REG0XA_DAT_S_WR_WAI_INT_MASK_POS (11) 
#define SDIO_REG0XA_DAT_S_WR_WAI_INT_MASK_MASK (0x1) 
	
#define SDIO_REG0XA_DAT_S_RD_BUS_INT_MASK_POS (12) 
#define SDIO_REG0XA_DAT_S_RD_BUS_INT_MASK_MASK (0x1) 

#define SDIO_REG0XA_TX_FIFO_NEED_WRITE_MASK_CG_POS (13) 
#define SDIO_REG0XA_TX_FIFO_NEED_WRITE_MASK_CG_MASK (0x1) 

#define SDIO_REG0XA_WRITE_WAIT_JUMP_SEL_POS (14) 
#define SDIO_REG0XA_WRITE_WAIT_JUMP_SEL_MASK (0x1) 

#define SDIO_REG0XA_IDLE_STOP_JUMP_SEL_POS (15) 
#define SDIO_REG0XA_IDLE_STOP_JUMP_SEL_MASK (0x1) 

#define SDIO_REG0XA_RESERVED0_POS (16) 
#define SDIO_REG0XA_RESERVED0_MASK (0xFFFF) 

/* REG_0x0B */
#define SDIO_REG0XB_ADDR  (SDIO_LL_REG_BASE  + 0xB*4) //REG ADDR :0x448b002c
#define SDIO_REG0XB_TX_FIFO_DIN_POS (0) 
#define SDIO_REG0XB_TX_FIFO_DIN_MASK (0xFFFFFFFF) 
	
/* REG_0x0C */
#define SDIO_REG0XC_ADDR  (SDIO_LL_REG_BASE  + 0xC*4) //REG ADDR :0x448b0030
#define SDIO_REG0XC_RX_FIFO_DOUT_POS (0) 
#define SDIO_REG0XC_RX_FIFO_DOUT_MASK (0xFFFFFFFF) 
	
/* REG_0x0D */
#define SDIO_REG0XD_ADDR  (SDIO_LL_REG_BASE  + 0xD*4) //REG ADDR :0x448b0034
#define SDIO_REG0XD_RX_FIFO_THRESHOLD_POS (0) 
#define SDIO_REG0XD_RX_FIFO_THRESHOLD_MASK (0xFF) 
	
#define SDIO_REG0XD_TX_FIFO_THRESHOLD_POS (8) 
#define SDIO_REG0XD_TX_FIFO_THRESHOLD_MASK (0xFF) 
	
#define SDIO_REG0XD_RX_FIFO_RST_POS (16) 
#define SDIO_REG0XD_RX_FIFO_RST_MASK (0x1) 
	
#define SDIO_REG0XD_TX_FIFO_RST_POS (17) 
#define SDIO_REG0XD_TX_FIFO_RST_MASK (0x1) 
	
#define SDIO_REG0XD_RXFIFO_RD_READY_POS (18) 
#define SDIO_REG0XD_RXFIFO_RD_READY_MASK (0x1) 
	
#define SDIO_REG0XD_TXFIFO_WR_READY_POS (19) 
#define SDIO_REG0XD_TXFIFO_WR_READY_MASK (0x1) 
	
#define SDIO_REG0XD_SD_STA_RST_POS (20) 
#define SDIO_REG0XD_SD_STA_RST_MASK (0x1) 
	
#define SDIO_REG0XD_SD_CLK_SEL_POS (21) 
#define SDIO_REG0XD_SD_CLK_SEL_MASK (0x3) 
	
#define SDIO_REG0XD_SD_RD_WAIT_SEL_POS (23) 
#define SDIO_REG0XD_SD_RD_WAIT_SEL_MASK (0x1) 
	
#define SDIO_REG0XD_SD_WR_WAIT_SEL_POS (24) 
#define SDIO_REG0XD_SD_WR_WAIT_SEL_MASK (0x1) 
	
#define SDIO_REG0XD_CLK_REC_SEL_POS (25) 
#define SDIO_REG0XD_CLK_REC_SEL_MASK (0x1) 

#define SDIO_REG0XD_SAMP_SEL_POS (26) 
#define SDIO_REG0XD_SAMP_SEL_MASK (0x1) 

#define SDIO_REG0XD_CLK_GATE_ON_POS (27) 
#define SDIO_REG0XD_CLK_GATE_ON_MASK (0x1) 

#define SDIO_REG0XD_HOST_WR_BLK_EN_POS (28) 
#define SDIO_REG0XD_HOST_WR_BLK_EN_MASK (0x1) 

#define SDIO_REG0XD_HOST_RD_BLK_EN_POS (29) 
#define SDIO_REG0XD_HOST_RD_BLK_EN_MASK (0x1) 

#define SDIO_REG0XD_RESERVED0_POS (30) 
#define SDIO_REG0XD_RESERVED0_MASK (0x3) 

/* REG_0x10 */
#define SDIO_REG0X10_ADDR  (SDIO_LL_REG_BASE  + 0x10*4) //REG ADDR :0x448b0040
#define SDIO_REG0X10_SD_SLAVE_POS (0) 
#define SDIO_REG0X10_SD_SLAVE_MASK (0x1) 
	
#define SDIO_REG0X10_DAT_S_RD_MUL_BLK_POS (1) 
#define SDIO_REG0X10_DAT_S_RD_MUL_BLK_MASK (0x1) 
	
#define SDIO_REG0X10_IO_CUR_STA_REG_POS (2) 
#define SDIO_REG0X10_IO_CUR_STA_REG_MASK (0x3) 
	
#define SDIO_REG0X10_CMD_52_STOP_CLR_POS (4) 
#define SDIO_REG0X10_CMD_52_STOP_CLR_MASK (0x1) 

#define SDIO_REG0X10_CMD_KEEP_DET_POS (5) 
#define SDIO_REG0X10_CMD_KEEP_DET_MASK (0x1) 

#define SDIO_REG0X10_RESERVED0_POS (6) 
#define SDIO_REG0X10_RESERVED0_MASK (0x3) 

#define SDIO_REG0X10_FIFO_SEND_CNT_POS (8) 
#define SDIO_REG0X10_FIFO_SEND_CNT_MASK (0xFF) 

#define SDIO_REG0X10_RESERVED1_POS (16) 
#define SDIO_REG0X10_RESERVED1_MASK (0xFFFF) 

/* REG_0x11 */
#define SDIO_REG0X11_ADDR  (SDIO_LL_REG_BASE  + 0x11*4) //REG ADDR :0x448b0044
#define SDIO_REG0X11_SD_SLAVE_RDAT_0_POS (0) 
#define SDIO_REG0X11_SD_SLAVE_RDAT_0_MASK (0xFFFFFFFF) 
	
	/* REG_0x12 */
#define SDIO_REG0X12_ADDR  (SDIO_LL_REG_BASE  + 0x12*4) //REG ADDR :0x448b0048
#define SDIO_REG0X12_SD_SLAVE_RDAT_1_POS (0) 
#define SDIO_REG0X12_SD_SLAVE_RDAT_1_MASK (0xFFFFFFFF) 
	
	/* REG_0x13 */
#define SDIO_REG0X13_ADDR  (SDIO_LL_REG_BASE  + 0x13*4) //REG ADDR :0x448b004c
#define SDIO_REG0X13_SD_SLAVE_WDAT_0_POS (0) 
#define SDIO_REG0X13_SD_SLAVE_WDAT_0_MASK (0xFFFFFFFF) 
	
	/* REG_0x14 */
#define SDIO_REG0X14_ADDR  (SDIO_LL_REG_BASE  + 0x14*4) //REG ADDR :0x448b0050
#define SDIO_REG0X14_SD_SLAVE_WDAT_1_POS (0) 
#define SDIO_REG0X14_SD_SLAVE_WDAT_1_MASK (0xFFFFFFFF) 
	
	/* REG_0x15 */
#define SDIO_SD_SLAVE_STATUS_ADDR  (SDIO_LL_REG_BASE  + 0x15*4) //REG ADDR :0x448b0054
#define SDIO_SD_SLAVE_STATUS_CMD_S_RES_DAT_RD_POS (0) 
#define SDIO_SD_SLAVE_STATUS_CMD_S_RES_DAT_RD_MASK (0x1) 
	
#define SDIO_SD_SLAVE_STATUS_CMD_S_RES_DAT_WR_POS (1) 
#define SDIO_SD_SLAVE_STATUS_CMD_S_RES_DAT_WR_MASK (0x1) 
	
#define SDIO_SD_SLAVE_STATUS_CMD_S_REC_BB_CNT_POS (2) 
#define SDIO_SD_SLAVE_STATUS_CMD_S_REC_BB_CNT_MASK (0x1FF) 
	
#define SDIO_SD_SLAVE_STATUS_CMD_S_REC_OP_CODE_POS (11) 
#define SDIO_SD_SLAVE_STATUS_CMD_S_REC_OP_CODE_MASK (0x1) 
	
#define SDIO_SD_SLAVE_STATUS_CMD_S_REC_BLK_MOD_POS (12) 
#define SDIO_SD_SLAVE_STATUS_CMD_S_REC_BLK_MOD_MASK (0x1) 
	
#define SDIO_SD_SLAVE_STATUS_SD_START_WR_EN_R3_POS (13) 
#define SDIO_SD_SLAVE_STATUS_SD_START_WR_EN_R3_MASK (0x1) 
	
#define SDIO_SD_SLAVE_STATUS_DAT_S_RD_BUS_4RD_POS (14) 
#define SDIO_SD_SLAVE_STATUS_DAT_S_RD_BUS_4RD_MASK (0x1) 
	
#define SDIO_SD_SLAVE_STATUS_CMD_S_RES_END_4RD_POS (15) 
#define SDIO_SD_SLAVE_STATUS_CMD_S_RES_END_4RD_MASK (0x1) 
	
#define SDIO_SD_SLAVE_STATUS_DAT_S_WR_WAI_4RD_POS (16) 
#define SDIO_SD_SLAVE_STATUS_DAT_S_WR_WAI_4RD_MASK (0x1) 
	
#define SDIO_SD_SLAVE_STATUS_RESERVED0_POS (17) 
#define SDIO_SD_SLAVE_STATUS_RESERVED0_MASK (0x7FFF) 

#define SDIO_LL_REG_END      (SDIO_SD_SLAVE_STATUS_ADDR) //REG_BASE:0x448B0054

#ifdef __cplusplus
}
#endif

