// Copyright 2020-2021 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif
#include <stdio.h>
#include <driver/hal/hal_gpio_types.h>
#include <soc/soc.h>

#define GPIO_DEV_MAP  \
{\
	{GPIO_0, {GPIO_DEV_UART2_TXD, GPIO_DEV_I2C2_SCL, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_1, {GPIO_DEV_UART2_RXD, GPIO_DEV_I2C2_SDA, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_2, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_3, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_4, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_5, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_6, {GPIO_DEV_CLK13M, GPIO_DEV_PWM0, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_7, {GPIO_DEV_WIFI_ACTIVE, GPIO_DEV_PWM1, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_8, {GPIO_DEV_BT_ACTIVE, GPIO_DEV_PWM2, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_9, {GPIO_DEV_BT_PRIORITY, GPIO_DEV_PWM3, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_10,{GPIO_DEV_UART1_RXD, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_11, {GPIO_DEV_UART1_TXD, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_12, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_13, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_14, {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SPI0_SCK, GPIO_DEV_QSPI_FLASH_CLK, GPIO_DEV_INVALID}},\
	{GPIO_15, {GPIO_DEV_SDIO_HOST_DATA3, GPIO_DEV_SPI0_CSN, GPIO_DEV_QSPI_FLASH_CSN, GPIO_DEV_INVALID}},\
	{GPIO_16, {GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SPI0_MOSI, GPIO_DEV_QSPI_IO0, GPIO_DEV_INVALID}},\
	{GPIO_17, {GPIO_DEV_SDIO_HOST_DATA0, GPIO_DEV_SPI0_MISO, GPIO_DEV_QSPI_IO1, GPIO_DEV_INVALID}},\
	{GPIO_18, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_19, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_20, {GPIO_DEV_I2C1_SCL, GPIO_DEV_JTAG_TCK, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_21, {GPIO_DEV_ADC6, GPIO_DEV_I2C1_SDA, GPIO_DEV_JTAG_TMS,  GPIO_DEV_INVALID}},\
	{GPIO_22, {GPIO_DEV_ADC5, GPIO_DEV_CLK26M, GPIO_DEV_JTAG_TDI, GPIO_DEV_TXEN}},\
	{GPIO_23, {GPIO_DEV_ADC3, GPIO_DEV_JTAG_TDO, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_24, {GPIO_DEV_ADC2, GPIO_DEV_LPO_CLK, GPIO_DEV_PWM4,  GPIO_DEV_INVALID}},\
	{GPIO_25, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_26, {GPIO_DEV_ADC1, GPIO_DEV_IRDA, GPIO_DEV_PWM5, GPIO_DEV_INVALID}},\
	{GPIO_27, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_28, {GPIO_DEV_ADC4, GPIO_DEV_RXEN,  GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
}

/* uart gpio pin map */
#define UART0_TX_PIN  GPIO_11
#define UART0_RX_PIN  GPIO_10
#define UART0_CTS_PIN GPIO_12
#define UART0_RTS_PIN GPIO_13

#define UART1_TX_PIN  GPIO_0
#define UART1_RX_PIN  GPIO_1

#define UART2_TX_PIN  GPIO_41
#define UART2_RX_PIN  GPIO_40

/* sdio host */
#define SDIO_HOST_GPIO_PIN_NUMBER    6
#define SDIO_HOST_GPIO_CLK_INDEX     0
#define SDIO_HOST_GPIO_CMD_INDEX     1
#define SDIO_HOST_GPIO_DATA0_INDEX   2
#define SDIO_HOST_GPIO_DATA1_INDEX   3
#define SDIO_HOST_GPIO_MAP \
{\
	{GPIO_8, GPIO_DEV_SDIO_HOST_CLK},\
	{GPIO_9, GPIO_DEV_SDIO_HOST_CMD},\
	{GPIO_10, GPIO_DEV_SDIO_HOST_DATA0},\
	{GPIO_35, GPIO_DEV_SDIO_HOST_DATA1},\
	{GPIO_34, GPIO_DEV_SDIO_HOST_DATA2},\
	{GPIO_36, GPIO_DEV_SDIO_HOST_DATA3},\
}

#define GPIO_MAP_TABLE(DEV_NUM, MODE_NUM, table) \
struct {\
	uint64_t gpio_bits;\
	gpio_dev_t devs[DEV_NUM];\
} table[MODE_NUM]

#define GPIO_I2C1_MAP_TABLE \
{\
	{BIT(0)|BIT(1), {GPIO_DEV_I2C1_SCL, GPIO_DEV_I2C1_SDA}},\
	{BIT64(42)|BIT64(43), {GPIO_DEV_I2C1_SCL, GPIO_DEV_I2C1_SDA}},\
}
#define GPIO_I2C1_USED_GPIO_NUM 2

#define GPIO_I2S_MAP_TABLE \
{\
	{BIT(6)|BIT(7)|BIT(8)|BIT(9), {GPIO_DEV_I2S1_CLK, GPIO_DEV_I2S1_SYNC, GPIO_DEV_I2S1_DIN, GPIO_DEV_I2S1_DOUT}},\
	{BIT64(40)|BIT64(41)|BIT64(42)|BIT64(43), {GPIO_DEV_I2S1_CLK, GPIO_DEV_I2S1_SYNC, GPIO_DEV_I2S1_DIN, GPIO_DEV_I2S1_DOUT}},\
}
#define GPIO_I2S_USED_GPIO_NUM 4

#define GPIO_SPI0_MAP_TABLE \
{\
	{BIT(14)|BIT(15)|BIT64(16)|BIT64(17), {GPIO_DEV_SPI0_SCK, GPIO_DEV_SPI0_CSN, GPIO_DEV_SPI0_MOSI, GPIO_DEV_SPI0_MISO}},\
	{BIT64(44)|BIT64(45)|BIT64(46)|BIT64(47), {GPIO_DEV_SPI0_CSN, GPIO_DEV_SPI0_SCK, GPIO_DEV_SPI0_MOSI, GPIO_DEV_SPI0_MISO}},\
}
#define GPIO_SPI0_USED_GPIO_NUM 4

#define GPIO_SDIO_ONE_LINE_MAP_TABLE \
{\
	{BIT(2)|BIT(3)|BIT(4), {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SDIO_HOST_DATA0}},\
	{BIT(14)|BIT(15)|BIT(16), {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SDIO_HOST_DATA0}},\
}
#define GPIO_SDIO_ONE_LINE_USED_GPIO_NUM 3

#define GPIO_SDIO_MAP_TABLE \
{\
	{BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(10)|BIT(11), {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SDIO_HOST_DATA0,GPIO_DEV_SDIO_HOST_DATA1,GPIO_DEV_SDIO_HOST_DATA2,GPIO_DEV_SDIO_HOST_DATA3}},\
	{BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19), {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SDIO_HOST_DATA0,GPIO_DEV_SDIO_HOST_DATA1,GPIO_DEV_SDIO_HOST_DATA2,GPIO_DEV_SDIO_HOST_DATA3}},\
}
#define GPIO_SDIO_USED_GPIO_NUM 6

#define GPIO_CTRL_LDO_OUTPUT_HIGH_MAP  \
{\
	/* GPIO_2, */\
	/* GPIO_28, */\
}

#define GPIO_CTRL_LDO_OUTPUT_LOW_MAP  \
{\
	/* GPIO_4, */\
	/* GPIO_26, */\
}

#ifdef __cplusplus
}
#endif
