// Copyright 2022-2023 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is a generated file, if you need to modify it, use the script to
// generate and modify all the struct.h, ll.h, reg.h, debug_dump.c files!

#pragma once


#ifdef __cplusplus
extern "C" {
#endif


#define SYS_DEVICE_ID_ADDR (SOC_SYS_REG_BASE + (0x0 << 2))

#define SYS_DEVICE_ID_DEVICEID_POS (0)
#define SYS_DEVICE_ID_DEVICEID_MASK (0xffffffff)

#define SYS_VERSION_ID_ADDR (SOC_SYS_REG_BASE + (0x1 << 2))

#define SYS_VERSION_ID_VERSIONID_POS (0)
#define SYS_VERSION_ID_VERSIONID_MASK (0xffffffff)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_ADDR (SOC_SYS_REG_BASE + (0x2 << 2))

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_BOOT_MODE_POS (0)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_BOOT_MODE_MASK (0x1)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED_BIT_1_7_POS (1)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED_BIT_1_7_MASK (0x7f)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_JTAG_CORE_SEL_POS (8)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_JTAG_CORE_SEL_MASK (0x1)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_FLASH_SEL_POS (9)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_FLASH_SEL_MASK (0x1)

#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED_BIT_10_31_POS (10)
#define SYS_CPU_STORAGE_CONNECT_OP_SELECT_RESERVED_BIT_10_31_MASK (0x3fffff)

#define SYS_CPU_CURRENT_RUN_STATUS_ADDR (SOC_SYS_REG_BASE + (0x3 << 2))

#define SYS_CPU_CURRENT_RUN_STATUS_CORE0_HALTED_POS (0)
#define SYS_CPU_CURRENT_RUN_STATUS_CORE0_HALTED_MASK (0x1)

#define SYS_CPU_CURRENT_RUN_STATUS_CORE1_HALTED_POS (1)
#define SYS_CPU_CURRENT_RUN_STATUS_CORE1_HALTED_MASK (0x1)

#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED_BIT_2_3_POS (2)
#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED_BIT_2_3_MASK (0x3)

#define SYS_CPU_CURRENT_RUN_STATUS_CPU0_SW_RESET_POS (4)
#define SYS_CPU_CURRENT_RUN_STATUS_CPU0_SW_RESET_MASK (0x1)

#define SYS_CPU_CURRENT_RUN_STATUS_CPU1_SW_RESET_POS (5)
#define SYS_CPU_CURRENT_RUN_STATUS_CPU1_SW_RESET_MASK (0x1)

#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED_BIT_6_7_POS (6)
#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED_BIT_6_7_MASK (0x3)

#define SYS_CPU_CURRENT_RUN_STATUS_CPU0_PWR_DW_STATE_POS (8)
#define SYS_CPU_CURRENT_RUN_STATUS_CPU0_PWR_DW_STATE_MASK (0x1)

#define SYS_CPU_CURRENT_RUN_STATUS_CPU1_PWR_DW_STATE_POS (9)
#define SYS_CPU_CURRENT_RUN_STATUS_CPU1_PWR_DW_STATE_MASK (0x1)

#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED_BIT_10_31_POS (10)
#define SYS_CPU_CURRENT_RUN_STATUS_RESERVED_BIT_10_31_MASK (0x3fffff)

#define SYS_CPU0_INT_HALT_CLK_OP_ADDR (SOC_SYS_REG_BASE + (0x4 << 2))

#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_SW_RST_POS (0)
#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_SW_RST_MASK (0x1)

#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_PWR_DW_POS (1)
#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_PWR_DW_MASK (0x1)

#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_INT_MASK_POS (2)
#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_INT_MASK_MASK (0x1)

#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_HALT_POS (3)
#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_HALT_MASK (0x1)

#define SYS_CPU0_INT_HALT_CLK_OP_RESERVED_4_7_POS (4)
#define SYS_CPU0_INT_HALT_CLK_OP_RESERVED_4_7_MASK (0xf)

#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_OFFSET_POS (8)
#define SYS_CPU0_INT_HALT_CLK_OP_CPU0_OFFSET_MASK (0xffffff)

#define SYS_CPU1_INT_HALT_CLK_OP_ADDR (SOC_SYS_REG_BASE + (0x5 << 2))

#define SYS_CPU1_INT_HALT_CLK_OP_CPU1_SW_RST_POS (0)
#define SYS_CPU1_INT_HALT_CLK_OP_CPU1_SW_RST_MASK (0x1)

#define SYS_CPU1_INT_HALT_CLK_OP_CPU1_PWR_DW_POS (1)
#define SYS_CPU1_INT_HALT_CLK_OP_CPU1_PWR_DW_MASK (0x1)

#define SYS_CPU1_INT_HALT_CLK_OP_CPU1_INT_MASK_POS (2)
#define SYS_CPU1_INT_HALT_CLK_OP_CPU1_INT_MASK_MASK (0x1)

#define SYS_CPU1_INT_HALT_CLK_OP_CPU1_HALT_POS (3)
#define SYS_CPU1_INT_HALT_CLK_OP_CPU1_HALT_MASK (0x1)

#define SYS_CPU1_INT_HALT_CLK_OP_CPU0_BUS_CLK_2DIV_POS (4)
#define SYS_CPU1_INT_HALT_CLK_OP_CPU0_BUS_CLK_2DIV_MASK (0x1)

#define SYS_CPU1_INT_HALT_CLK_OP_RESERVED_5_7_POS (5)
#define SYS_CPU1_INT_HALT_CLK_OP_RESERVED_5_7_MASK (0x7)

#define SYS_CPU1_INT_HALT_CLK_OP_CPU1_OFFSET_POS (8)
#define SYS_CPU1_INT_HALT_CLK_OP_CPU1_OFFSET_MASK (0xffffff)

#define SYS_RESERVED_REG0X6_ADDR (SOC_SYS_REG_BASE + (0x6 << 2))

#define SYS_RESERVED_REG0X6_RESERVED_0_31_POS (0)
#define SYS_RESERVED_REG0X6_RESERVED_0_31_MASK (0xffffffff)

#define SYS_CPU_CLK_DIV_MODE1_ADDR (SOC_SYS_REG_BASE + (0x8 << 2))

#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_CORE_POS (0)
#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_CORE_MASK (0xf)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_CORE_POS (4)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_CORE_MASK (0x3)

#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_BUS_POS (6)
#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_BUS_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_RESERVED_BIT_7_7_POS (7)
#define SYS_CPU_CLK_DIV_MODE1_RESERVED_BIT_7_7_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_UART0_POS (8)
#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_UART0_MASK (0x3)

#define SYS_CPU_CLK_DIV_MODE1_CLKSEL_UART0_POS (10)
#define SYS_CPU_CLK_DIV_MODE1_CLKSEL_UART0_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_UART1_POS (11)
#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_UART1_MASK (0x3)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_UART1_POS (13)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_UART1_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_UART2_POS (14)
#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_UART2_MASK (0x3)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_UART2_POS (16)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_UART2_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_SADC_POS (17)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_SADC_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_PWM0_POS (18)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_PWM0_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_PWM1_POS (19)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_PWM1_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_TIM0_POS (20)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_TIM0_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_TIM1_POS (21)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_TIM1_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_TIM2_POS (22)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_TIM2_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_RESERVED_BIT_23_23_POS (23)
#define SYS_CPU_CLK_DIV_MODE1_RESERVED_BIT_23_23_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_I2S_POS (24)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_I2S_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_AUD_POS (25)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_AUD_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_JPEG_POS (26)
#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_JPEG_MASK (0xf)

#define SYS_CPU_CLK_DIV_MODE1_CKSEL_JPEG_POS (30)
#define SYS_CPU_CLK_DIV_MODE1_CKSEL_JPEG_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_DISP_L_POS (31)
#define SYS_CPU_CLK_DIV_MODE1_CLKDIV_DISP_L_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE2_ADDR (SOC_SYS_REG_BASE + (0x9 << 2))

#define SYS_CPU_CLK_DIV_MODE2_CLKDIV_DISP_H_POS (0)
#define SYS_CPU_CLK_DIV_MODE2_CLKDIV_DISP_H_MASK (0x7)

#define SYS_CPU_CLK_DIV_MODE2_CKSEL_DISP_POS (3)
#define SYS_CPU_CLK_DIV_MODE2_CKSEL_DISP_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE2_CKDIV_PSRAM_POS (4)
#define SYS_CPU_CLK_DIV_MODE2_CKDIV_PSRAM_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE2_CKSEL_PSRAM_POS (5)
#define SYS_CPU_CLK_DIV_MODE2_CKSEL_PSRAM_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE2_CKDIV_QSPI0_POS (6)
#define SYS_CPU_CLK_DIV_MODE2_CKDIV_QSPI0_MASK (0xf)

#define SYS_CPU_CLK_DIV_MODE2_RESERVED_10_13_POS (10)
#define SYS_CPU_CLK_DIV_MODE2_RESERVED_10_13_MASK (0xf)

#define SYS_CPU_CLK_DIV_MODE2_CKDIV_SDIO_POS (14)
#define SYS_CPU_CLK_DIV_MODE2_CKDIV_SDIO_MASK (0x7)

#define SYS_CPU_CLK_DIV_MODE2_CKSEL_SDIO_POS (17)
#define SYS_CPU_CLK_DIV_MODE2_CKSEL_SDIO_MASK (0x1)

#define SYS_CPU_CLK_DIV_MODE2_CKDIV_AUXS_POS (18)
#define SYS_CPU_CLK_DIV_MODE2_CKDIV_AUXS_MASK (0xf)

#define SYS_CPU_CLK_DIV_MODE2_CKSEL_AUXS_POS (22)
#define SYS_CPU_CLK_DIV_MODE2_CKSEL_AUXS_MASK (0x3)

#define SYS_CPU_CLK_DIV_MODE2_CKSEL_FLASH_POS (24)
#define SYS_CPU_CLK_DIV_MODE2_CKSEL_FLASH_MASK (0x3)

#define SYS_CPU_CLK_DIV_MODE2_CKDIV_FLASH_POS (26)
#define SYS_CPU_CLK_DIV_MODE2_CKDIV_FLASH_MASK (0x3)

#define SYS_CPU_CLK_DIV_MODE2_CKDIV_I2S0_POS (28)
#define SYS_CPU_CLK_DIV_MODE2_CKDIV_I2S0_MASK (0x7)

#define SYS_CPU_CLK_DIV_MODE2_RESERVED_BIT_31_31_POS (31)
#define SYS_CPU_CLK_DIV_MODE2_RESERVED_BIT_31_31_MASK (0x1)

#define SYS_CPU_26M_WDT_CLK_DIV_ADDR (SOC_SYS_REG_BASE + (0xa << 2))

#define SYS_CPU_26M_WDT_CLK_DIV_CKDIV_26M_POS (0)
#define SYS_CPU_26M_WDT_CLK_DIV_CKDIV_26M_MASK (0x3)

#define SYS_CPU_26M_WDT_CLK_DIV_CKDIV_WDT_POS (2)
#define SYS_CPU_26M_WDT_CLK_DIV_CKDIV_WDT_MASK (0x3)

#define SYS_CPU_26M_WDT_CLK_DIV_CLKSEL_SPI0_POS (4)
#define SYS_CPU_26M_WDT_CLK_DIV_CLKSEL_SPI0_MASK (0x1)

#define SYS_CPU_26M_WDT_CLK_DIV_CLKSEL_SPI1_POS (5)
#define SYS_CPU_26M_WDT_CLK_DIV_CLKSEL_SPI1_MASK (0x1)

#define SYS_CPU_26M_WDT_CLK_DIV_RESERVED_BIT_6_31_POS (6)
#define SYS_CPU_26M_WDT_CLK_DIV_RESERVED_BIT_6_31_MASK (0x3ffffff)

#define SYS_CPU_ANASPI_FREQ_ADDR (SOC_SYS_REG_BASE + (0xb << 2))

#define SYS_CPU_ANASPI_FREQ_ANASPI_FREQ_POS (0)
#define SYS_CPU_ANASPI_FREQ_ANASPI_FREQ_MASK (0x3f)

#define SYS_CPU_ANASPI_FREQ_RESERVED_BIT_6_31_POS (6)
#define SYS_CPU_ANASPI_FREQ_RESERVED_BIT_6_31_MASK (0x3ffffff)

#define SYS_CPU_DEVICE_CLK_ENABLE_ADDR (SOC_SYS_REG_BASE + (0xc << 2))

#define SYS_CPU_DEVICE_CLK_ENABLE_I2C0_CKEN_POS (0)
#define SYS_CPU_DEVICE_CLK_ENABLE_I2C0_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_SPI0_CKEN_POS (1)
#define SYS_CPU_DEVICE_CLK_ENABLE_SPI0_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_UART0_CKEN_POS (2)
#define SYS_CPU_DEVICE_CLK_ENABLE_UART0_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_PWM0_CKEN_POS (3)
#define SYS_CPU_DEVICE_CLK_ENABLE_PWM0_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_TIM0_CKEN_POS (4)
#define SYS_CPU_DEVICE_CLK_ENABLE_TIM0_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_SADC_CKEN_POS (5)
#define SYS_CPU_DEVICE_CLK_ENABLE_SADC_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_IRDA_CKEN_POS (6)
#define SYS_CPU_DEVICE_CLK_ENABLE_IRDA_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_EFUSE_CKEN_POS (7)
#define SYS_CPU_DEVICE_CLK_ENABLE_EFUSE_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_I2C1_CKEN_POS (8)
#define SYS_CPU_DEVICE_CLK_ENABLE_I2C1_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_SPI1_CKEN_POS (9)
#define SYS_CPU_DEVICE_CLK_ENABLE_SPI1_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_UART1_CKEN_POS (10)
#define SYS_CPU_DEVICE_CLK_ENABLE_UART1_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_UART2_CKEN_POS (11)
#define SYS_CPU_DEVICE_CLK_ENABLE_UART2_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_PWM1_CKEN_POS (12)
#define SYS_CPU_DEVICE_CLK_ENABLE_PWM1_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_TIM1_CKEN_POS (13)
#define SYS_CPU_DEVICE_CLK_ENABLE_TIM1_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_TIM2_CKEN_POS (14)
#define SYS_CPU_DEVICE_CLK_ENABLE_TIM2_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_OTP_CKEN_POS (15)
#define SYS_CPU_DEVICE_CLK_ENABLE_OTP_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_I2S_CKEN_POS (16)
#define SYS_CPU_DEVICE_CLK_ENABLE_I2S_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_USB_CKEN_POS (17)
#define SYS_CPU_DEVICE_CLK_ENABLE_USB_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_CAN_CKEN_POS (18)
#define SYS_CPU_DEVICE_CLK_ENABLE_CAN_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_PSRAM_CKEN_POS (19)
#define SYS_CPU_DEVICE_CLK_ENABLE_PSRAM_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_QSPI0_CKEN_POS (20)
#define SYS_CPU_DEVICE_CLK_ENABLE_QSPI0_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_QSPI1_CKEN_POS (21)
#define SYS_CPU_DEVICE_CLK_ENABLE_QSPI1_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_SDIO_CKEN_POS (22)
#define SYS_CPU_DEVICE_CLK_ENABLE_SDIO_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_AUXS_CKEN_POS (23)
#define SYS_CPU_DEVICE_CLK_ENABLE_AUXS_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_BTDM_CKEN_POS (24)
#define SYS_CPU_DEVICE_CLK_ENABLE_BTDM_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_XVR_CKEN_POS (25)
#define SYS_CPU_DEVICE_CLK_ENABLE_XVR_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_MAC_CKEN_POS (26)
#define SYS_CPU_DEVICE_CLK_ENABLE_MAC_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_PHY_CKEN_POS (27)
#define SYS_CPU_DEVICE_CLK_ENABLE_PHY_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_JPEG_CKEN_POS (28)
#define SYS_CPU_DEVICE_CLK_ENABLE_JPEG_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_DISP_CKEN_POS (29)
#define SYS_CPU_DEVICE_CLK_ENABLE_DISP_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_AUD_CKEN_POS (30)
#define SYS_CPU_DEVICE_CLK_ENABLE_AUD_CKEN_MASK (0x1)

#define SYS_CPU_DEVICE_CLK_ENABLE_WDT_CKEN_POS (31)
#define SYS_CPU_DEVICE_CLK_ENABLE_WDT_CKEN_MASK (0x1)

#define SYS_RESERVER_REG0XD_ADDR (SOC_SYS_REG_BASE + (0xd << 2))

#define SYS_RESERVER_REG0XD_H264_CKEN_POS (0)
#define SYS_RESERVER_REG0XD_H264_CKEN_MASK (0x1)

#define SYS_RESERVER_REG0XD_I2S1_CKEN_POS (1)
#define SYS_RESERVER_REG0XD_I2S1_CKEN_MASK (0x1)

#define SYS_RESERVER_REG0XD_I2S2_CKEN_POS (2)
#define SYS_RESERVER_REG0XD_I2S2_CKEN_MASK (0x1)

#define SYS_RESERVER_REG0XD_YUV_CKEN_POS (3)
#define SYS_RESERVER_REG0XD_YUV_CKEN_MASK (0x1)

#define SYS_RESERVER_REG0XD_SLCD_CKEN_POS (4)
#define SYS_RESERVER_REG0XD_SLCD_CKEN_MASK (0x1)

#define SYS_RESERVER_REG0XD_RESERVED_5_31_POS (5)
#define SYS_RESERVER_REG0XD_RESERVED_5_31_MASK (0x7ffffff)

#define SYS_CPU_DEVICE_MEM_CTRL1_ADDR (SOC_SYS_REG_BASE + (0xe << 2))

#define SYS_CPU_DEVICE_MEM_CTRL1_UART1_MEM_SD_POS (0)
#define SYS_CPU_DEVICE_MEM_CTRL1_UART1_MEM_SD_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_UART2_POS (1)
#define SYS_CPU_DEVICE_MEM_CTRL1_UART2_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_SPI1_POS (2)
#define SYS_CPU_DEVICE_MEM_CTRL1_SPI1_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_SDIO_POS (3)
#define SYS_CPU_DEVICE_MEM_CTRL1_SDIO_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_USB_POS (4)
#define SYS_CPU_DEVICE_MEM_CTRL1_USB_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_CAN_POS (5)
#define SYS_CPU_DEVICE_MEM_CTRL1_CAN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_QSPI0_POS (6)
#define SYS_CPU_DEVICE_MEM_CTRL1_QSPI0_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_QSPI1_POS (7)
#define SYS_CPU_DEVICE_MEM_CTRL1_QSPI1_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_PRAM_POS (8)
#define SYS_CPU_DEVICE_MEM_CTRL1_PRAM_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_FFT_POS (9)
#define SYS_CPU_DEVICE_MEM_CTRL1_FFT_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_ABC_POS (10)
#define SYS_CPU_DEVICE_MEM_CTRL1_ABC_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_AUD_POS (11)
#define SYS_CPU_DEVICE_MEM_CTRL1_AUD_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_I2S0_POS (12)
#define SYS_CPU_DEVICE_MEM_CTRL1_I2S0_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_I2S1_POS (13)
#define SYS_CPU_DEVICE_MEM_CTRL1_I2S1_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_I2S2_POS (14)
#define SYS_CPU_DEVICE_MEM_CTRL1_I2S2_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_JPGE_POS (15)
#define SYS_CPU_DEVICE_MEM_CTRL1_JPGE_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_YUV_POS (16)
#define SYS_CPU_DEVICE_MEM_CTRL1_YUV_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_JPGD_POS (17)
#define SYS_CPU_DEVICE_MEM_CTRL1_JPGD_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_DISP_POS (18)
#define SYS_CPU_DEVICE_MEM_CTRL1_DISP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_DMAD_POS (19)
#define SYS_CPU_DEVICE_MEM_CTRL1_DMAD_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_H26F_POS (20)
#define SYS_CPU_DEVICE_MEM_CTRL1_H26F_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_MAC_POS (21)
#define SYS_CPU_DEVICE_MEM_CTRL1_MAC_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_PHY_POS (22)
#define SYS_CPU_DEVICE_MEM_CTRL1_PHY_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_XVR_POS (23)
#define SYS_CPU_DEVICE_MEM_CTRL1_XVR_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_IRDA_POS (24)
#define SYS_CPU_DEVICE_MEM_CTRL1_IRDA_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_LA_POS (25)
#define SYS_CPU_DEVICE_MEM_CTRL1_LA_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_FLSH_POS (26)
#define SYS_CPU_DEVICE_MEM_CTRL1_FLSH_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_UART_POS (27)
#define SYS_CPU_DEVICE_MEM_CTRL1_UART_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_SPI0_POS (28)
#define SYS_CPU_DEVICE_MEM_CTRL1_SPI0_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_ENC_POS (29)
#define SYS_CPU_DEVICE_MEM_CTRL1_ENC_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_DMA0_POS (30)
#define SYS_CPU_DEVICE_MEM_CTRL1_DMA0_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL1_DMA1_POS (31)
#define SYS_CPU_DEVICE_MEM_CTRL1_DMA1_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_ADDR (SOC_SYS_REG_BASE + (0xf << 2))

#define SYS_CPU_DEVICE_MEM_CTRL2_UART1_MEM_DS_POS (0)
#define SYS_CPU_DEVICE_MEM_CTRL2_UART1_MEM_DS_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_UART2_POS (1)
#define SYS_CPU_DEVICE_MEM_CTRL2_UART2_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_SPI1_POS (2)
#define SYS_CPU_DEVICE_MEM_CTRL2_SPI1_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_SDIO_POS (3)
#define SYS_CPU_DEVICE_MEM_CTRL2_SDIO_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_USB_POS (4)
#define SYS_CPU_DEVICE_MEM_CTRL2_USB_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_CAN_POS (5)
#define SYS_CPU_DEVICE_MEM_CTRL2_CAN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_QSPI0_POS (6)
#define SYS_CPU_DEVICE_MEM_CTRL2_QSPI0_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_QSPI1_POS (7)
#define SYS_CPU_DEVICE_MEM_CTRL2_QSPI1_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_PRAM_POS (8)
#define SYS_CPU_DEVICE_MEM_CTRL2_PRAM_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_FFT_POS (9)
#define SYS_CPU_DEVICE_MEM_CTRL2_FFT_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_ABC_POS (10)
#define SYS_CPU_DEVICE_MEM_CTRL2_ABC_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_AUD_POS (11)
#define SYS_CPU_DEVICE_MEM_CTRL2_AUD_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_I2S0_POS (12)
#define SYS_CPU_DEVICE_MEM_CTRL2_I2S0_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_I2S1_POS (13)
#define SYS_CPU_DEVICE_MEM_CTRL2_I2S1_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_I2S2_POS (14)
#define SYS_CPU_DEVICE_MEM_CTRL2_I2S2_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_JPGE_POS (15)
#define SYS_CPU_DEVICE_MEM_CTRL2_JPGE_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_YUV_POS (16)
#define SYS_CPU_DEVICE_MEM_CTRL2_YUV_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_JPGD_POS (17)
#define SYS_CPU_DEVICE_MEM_CTRL2_JPGD_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_DISP_POS (18)
#define SYS_CPU_DEVICE_MEM_CTRL2_DISP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_DMAD_POS (19)
#define SYS_CPU_DEVICE_MEM_CTRL2_DMAD_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_H26F_POS (20)
#define SYS_CPU_DEVICE_MEM_CTRL2_H26F_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_MAC_POS (21)
#define SYS_CPU_DEVICE_MEM_CTRL2_MAC_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_PHY_POS (22)
#define SYS_CPU_DEVICE_MEM_CTRL2_PHY_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_XVR_POS (23)
#define SYS_CPU_DEVICE_MEM_CTRL2_XVR_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_IRDA_POS (24)
#define SYS_CPU_DEVICE_MEM_CTRL2_IRDA_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_LA_POS (25)
#define SYS_CPU_DEVICE_MEM_CTRL2_LA_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_FLSH_POS (26)
#define SYS_CPU_DEVICE_MEM_CTRL2_FLSH_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_UART_POS (27)
#define SYS_CPU_DEVICE_MEM_CTRL2_UART_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_SPI0_POS (28)
#define SYS_CPU_DEVICE_MEM_CTRL2_SPI0_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_ENC_POS (29)
#define SYS_CPU_DEVICE_MEM_CTRL2_ENC_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_DMA0_POS (30)
#define SYS_CPU_DEVICE_MEM_CTRL2_DMA0_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL2_DMA1_POS (31)
#define SYS_CPU_DEVICE_MEM_CTRL2_DMA1_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_ADDR (SOC_SYS_REG_BASE + (0x10 << 2))

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM1_POS (0)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM1_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM2_POS (1)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM2_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM3_POS (2)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM3_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_ENCP_POS (3)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_ENCP_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_BAKP_POS (4)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_BAKP_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_AHBP_POS (5)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_AHBP_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_AUDP_POS (6)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_AUDP_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_VIDP_POS (7)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_VIDP_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_BTSP_POS (8)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_BTSP_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_WIFP_MAC_POS (9)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_WIFP_MAC_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_WIFP_PHY_POS (10)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_WIFP_PHY_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM0_POS (11)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM0_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM4_POS (12)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_MEM4_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_OFDM_POS (13)
#define SYS_CPU_POWER_SLEEP_WAKEUP_PWD_OFDM_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_TCM0_PGEN_POS (14)
#define SYS_CPU_POWER_SLEEP_WAKEUP_TCM0_PGEN_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_ROM_PGEN_POS (15)
#define SYS_CPU_POWER_SLEEP_WAKEUP_ROM_PGEN_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_NEED_FLASH_IDLE_POS (16)
#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_NEED_FLASH_IDLE_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_NEED_CPU1_WFI_POS (17)
#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_NEED_CPU1_WFI_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_NEED_CPU0_WFI_POS (18)
#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_NEED_CPU0_WFI_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_GLOBAL_POS (19)
#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_EN_GLOBAL_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_BUS_IDLE_BYPASS_POS (20)
#define SYS_CPU_POWER_SLEEP_WAKEUP_SLEEP_BUS_IDLE_BYPASS_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_BTS_WAKEUP_PLATFORM_EN_POS (21)
#define SYS_CPU_POWER_SLEEP_WAKEUP_BTS_WAKEUP_PLATFORM_EN_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_BTS_SOFT_WAKEUP_REQ_POS (22)
#define SYS_CPU_POWER_SLEEP_WAKEUP_BTS_SOFT_WAKEUP_REQ_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_ROM_RD_DISABLE_POS (23)
#define SYS_CPU_POWER_SLEEP_WAKEUP_ROM_RD_DISABLE_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_OTP_RD_DISABLE_POS (24)
#define SYS_CPU_POWER_SLEEP_WAKEUP_OTP_RD_DISABLE_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_TCM1_PGEN_POS (25)
#define SYS_CPU_POWER_SLEEP_WAKEUP_TCM1_PGEN_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_CPU0_SUBPWDM_EN_POS (26)
#define SYS_CPU_POWER_SLEEP_WAKEUP_CPU0_SUBPWDM_EN_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_CPU1_SUBPWDM_EN_POS (27)
#define SYS_CPU_POWER_SLEEP_WAKEUP_CPU1_SUBPWDM_EN_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_SHARE_MEM_CLKGATING_DISABLE_POS (28)
#define SYS_CPU_POWER_SLEEP_WAKEUP_SHARE_MEM_CLKGATING_DISABLE_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_CPU0_TICKTIMER_32K_ENABLE_POS (29)
#define SYS_CPU_POWER_SLEEP_WAKEUP_CPU0_TICKTIMER_32K_ENABLE_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_CPU1_TICKTIMER_32K_ENABLE_POS (30)
#define SYS_CPU_POWER_SLEEP_WAKEUP_CPU1_TICKTIMER_32K_ENABLE_MASK (0x1)

#define SYS_CPU_POWER_SLEEP_WAKEUP_RESERVED_BIT_31_31_POS (31)
#define SYS_CPU_POWER_SLEEP_WAKEUP_RESERVED_BIT_31_31_MASK (0x1)

#define SYS_RESERVER_REG0X11_ADDR (SOC_SYS_REG_BASE + (0x11 << 2))

#define SYS_RESERVER_REG0X11_RESERVED_0_31_POS (0)
#define SYS_RESERVER_REG0X11_RESERVED_0_31_MASK (0xffffffff)

#define SYS_CPU_DEVICE_MEM_CTRL3_ADDR (SOC_SYS_REG_BASE + (0x12 << 2))

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM0_MEM_DS_DEEP_SLEEP_POS (0)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM0_MEM_DS_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM1_DEEP_SLEEP_POS (1)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM1_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM2_DEEP_SLEEP_POS (2)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM2_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM3_DEEP_SLEEP_POS (3)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM3_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM4_DEEP_SLEEP_POS (4)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM4_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_ICACHE_ITAG_DEEP_SLEEP_POS (5)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_ICACHE_ITAG_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_DCACHE_DTAG_DEEP_SLEEP_POS (6)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_DCACHE_DTAG_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_ICACHE_ITAG_DEEP_SLEEP_POS (7)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_ICACHE_ITAG_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_DCACHE_DTAG_DEEP_SLEEP_POS (8)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_DCACHE_DTAG_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_ITCM_DEEP_SLEEP_POS (9)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_ITCM_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_DTCM_DEEP_SLEEP_POS (10)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_DTCM_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_ITCM_DEEP_SLEEP_POS (11)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_ITCM_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_DTCM_DEEP_SLEEP_POS (12)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_DTCM_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_ROTT_DEEP_SLEEP_POS (13)
#define SYS_CPU_DEVICE_MEM_CTRL3_ROTT_DEEP_SLEEP_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RESERVED0_POS (14)
#define SYS_CPU_DEVICE_MEM_CTRL3_RESERVED0_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RESERVED1_POS (15)
#define SYS_CPU_DEVICE_MEM_CTRL3_RESERVED1_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM0_MEM_SD_SHUTDOWN_POS (16)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM0_MEM_SD_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM1_SHUTDOWN_POS (17)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM1_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM2_SHUTDOWN_POS (18)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM2_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM3_SHUTDOWN_POS (19)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM3_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RAM4_SHUTDOWN_POS (20)
#define SYS_CPU_DEVICE_MEM_CTRL3_RAM4_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_ICACHE_ITAG_SHUTDOWN_POS (21)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_ICACHE_ITAG_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_DCACHE_DTAG_SHUTDOWN_POS (22)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_DCACHE_DTAG_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_ICACHE_ITAG_SHUTDOWN_POS (23)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_ICACHE_ITAG_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_DCACHE_DTAG_SHUTDOWN_POS (24)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_DCACHE_DTAG_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_ITCM_SHUTDOWN_POS (25)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_ITCM_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_DTCM_SHUTDOWN_POS (26)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU0_DTCM_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_ITCM_SHUTDOWN_POS (27)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_ITCM_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_DTCM_SHUTDOWN_POS (28)
#define SYS_CPU_DEVICE_MEM_CTRL3_CPU1_DTCM_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_ROTT_SHUTDOWN_POS (29)
#define SYS_CPU_DEVICE_MEM_CTRL3_ROTT_SHUTDOWN_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RESERVED2_POS (30)
#define SYS_CPU_DEVICE_MEM_CTRL3_RESERVED2_MASK (0x1)

#define SYS_CPU_DEVICE_MEM_CTRL3_RESERVED3_POS (31)
#define SYS_CPU_DEVICE_MEM_CTRL3_RESERVED3_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_ADDR (SOC_SYS_REG_BASE + (0x20 << 2))

#define SYS_CPU0_INT_0_31_EN_CPU0_DMA0_NSEC_INTR_EN_POS (0)
#define SYS_CPU0_INT_0_31_EN_CPU0_DMA0_NSEC_INTR_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_ENCP_SEC_INTR_EN_POS (1)
#define SYS_CPU0_INT_0_31_EN_CPU0_ENCP_SEC_INTR_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_ENCP_NSEC_INTR_EN_POS (2)
#define SYS_CPU0_INT_0_31_EN_CPU0_ENCP_NSEC_INTR_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_TIMER0_INT_EN_POS (3)
#define SYS_CPU0_INT_0_31_EN_CPU0_TIMER0_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_UART_INT_EN_POS (4)
#define SYS_CPU0_INT_0_31_EN_CPU0_UART_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_PWM0_INT_EN_POS (5)
#define SYS_CPU0_INT_0_31_EN_CPU0_PWM0_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_I2C0_INT_EN_POS (6)
#define SYS_CPU0_INT_0_31_EN_CPU0_I2C0_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_SPI0_INT_EN_POS (7)
#define SYS_CPU0_INT_0_31_EN_CPU0_SPI0_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_SADC_INT_EN_POS (8)
#define SYS_CPU0_INT_0_31_EN_CPU0_SADC_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_IRDA_INT_EN_POS (9)
#define SYS_CPU0_INT_0_31_EN_CPU0_IRDA_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_SDIO_INT_EN_POS (10)
#define SYS_CPU0_INT_0_31_EN_CPU0_SDIO_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_GDMA_INT_EN_POS (11)
#define SYS_CPU0_INT_0_31_EN_CPU0_GDMA_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_LA_INT_EN_POS (12)
#define SYS_CPU0_INT_0_31_EN_CPU0_LA_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_TIMER1_INT_EN_POS (13)
#define SYS_CPU0_INT_0_31_EN_CPU0_TIMER1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_I2C1_INT_EN_POS (14)
#define SYS_CPU0_INT_0_31_EN_CPU0_I2C1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_UART1_INT_EN_POS (15)
#define SYS_CPU0_INT_0_31_EN_CPU0_UART1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_UART2_INT_EN_POS (16)
#define SYS_CPU0_INT_0_31_EN_CPU0_UART2_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_SPI1_INT_EN_POS (17)
#define SYS_CPU0_INT_0_31_EN_CPU0_SPI1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_CAN_INT_EN_POS (18)
#define SYS_CPU0_INT_0_31_EN_CPU0_CAN_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_USB_INT_EN_POS (19)
#define SYS_CPU0_INT_0_31_EN_CPU0_USB_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_QSPI0_INT_EN_POS (20)
#define SYS_CPU0_INT_0_31_EN_CPU0_QSPI0_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_FFT_INT_EN_POS (21)
#define SYS_CPU0_INT_0_31_EN_CPU0_FFT_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_SBC_INT_EN_POS (22)
#define SYS_CPU0_INT_0_31_EN_CPU0_SBC_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_AUD_INT_EN_POS (23)
#define SYS_CPU0_INT_0_31_EN_CPU0_AUD_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_I2S0_INT_EN_POS (24)
#define SYS_CPU0_INT_0_31_EN_CPU0_I2S0_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_JPEGENC_INT_EN_POS (25)
#define SYS_CPU0_INT_0_31_EN_CPU0_JPEGENC_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_JPEGDEC_INT_EN_POS (26)
#define SYS_CPU0_INT_0_31_EN_CPU0_JPEGDEC_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_LCD_DISPLAY_INT_EN_POS (27)
#define SYS_CPU0_INT_0_31_EN_CPU0_LCD_DISPLAY_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_DMA2D_INT_EN_POS (28)
#define SYS_CPU0_INT_0_31_EN_CPU0_DMA2D_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_WIFI_INT_PHY_MPB_EN_POS (29)
#define SYS_CPU0_INT_0_31_EN_CPU0_WIFI_INT_PHY_MPB_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_WIFI_INT_PHY_RIU_EN_POS (30)
#define SYS_CPU0_INT_0_31_EN_CPU0_WIFI_INT_PHY_RIU_EN_MASK (0x1)

#define SYS_CPU0_INT_0_31_EN_CPU0_WIFI_MAC_INT_TX_RX_TIMER_EN_POS (31)
#define SYS_CPU0_INT_0_31_EN_CPU0_WIFI_MAC_INT_TX_RX_TIMER_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_ADDR (SOC_SYS_REG_BASE + (0x21 << 2))

#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_TX_RX_MISC_EN_POS (0)
#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_TX_RX_MISC_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_RX_TRIGGER_EN_POS (1)
#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_RX_TRIGGER_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_TX_TRIGGER_EN_POS (2)
#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_TX_TRIGGER_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_PROT_TRIGGER_EN_POS (3)
#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_PROT_TRIGGER_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_GEN_EN_POS (4)
#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_MAC_INT_GEN_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_HSU_IRQ_EN_POS (5)
#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_HSU_IRQ_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_INT_MAC_WAKEUP_EN_POS (6)
#define SYS_CPU0_INT_32_63_EN_CPU0_WIFI_INT_MAC_WAKEUP_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_DM_IRQ_EN_POS (7)
#define SYS_CPU0_INT_32_63_EN_CPU0_DM_IRQ_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_BLE_IRQ_EN_POS (8)
#define SYS_CPU0_INT_32_63_EN_CPU0_BLE_IRQ_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_BT_IRQ_EN_POS (9)
#define SYS_CPU0_INT_32_63_EN_CPU0_BT_IRQ_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_QSPI1_INT_EN_POS (10)
#define SYS_CPU0_INT_32_63_EN_CPU0_QSPI1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_PWM1_INT_EN_POS (11)
#define SYS_CPU0_INT_32_63_EN_CPU0_PWM1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_I2S1_INT_EN_POS (12)
#define SYS_CPU0_INT_32_63_EN_CPU0_I2S1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_I2S2_INT_EN_POS (13)
#define SYS_CPU0_INT_32_63_EN_CPU0_I2S2_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_H264_INT_EN_POS (14)
#define SYS_CPU0_INT_32_63_EN_CPU0_H264_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_SDMADC_INT_EN_POS (15)
#define SYS_CPU0_INT_32_63_EN_CPU0_SDMADC_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_MBOX0_INT_EN_POS (16)
#define SYS_CPU0_INT_32_63_EN_CPU0_MBOX0_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_MBOX1_INT_EN_POS (17)
#define SYS_CPU0_INT_32_63_EN_CPU0_MBOX1_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_BMC64_INT_EN_POS (18)
#define SYS_CPU0_INT_32_63_EN_CPU0_BMC64_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_DPLL_UNLOCK_INT_EN_POS (19)
#define SYS_CPU0_INT_32_63_EN_CPU0_DPLL_UNLOCK_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_TOUCHED_INT_EN_POS (20)
#define SYS_CPU0_INT_32_63_EN_CPU0_TOUCHED_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_USBPLUG_INT_EN_POS (21)
#define SYS_CPU0_INT_32_63_EN_CPU0_USBPLUG_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_RTC_INT_EN_POS (22)
#define SYS_CPU0_INT_32_63_EN_CPU0_RTC_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_GPIO_INT_EN_POS (23)
#define SYS_CPU0_INT_32_63_EN_CPU0_GPIO_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_DMA1_SEC_INT_EN_POS (24)
#define SYS_CPU0_INT_32_63_EN_CPU0_DMA1_SEC_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_DMA1_NSEC_INT_EN_POS (25)
#define SYS_CPU0_INT_32_63_EN_CPU0_DMA1_NSEC_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_YUVB_INT_EN_POS (26)
#define SYS_CPU0_INT_32_63_EN_CPU0_YUVB_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_CPU0_ROTT_INT_EN_POS (27)
#define SYS_CPU0_INT_32_63_EN_CPU0_ROTT_INT_EN_MASK (0x1)

#define SYS_CPU0_INT_32_63_EN_RESERVED0_POS (28)
#define SYS_CPU0_INT_32_63_EN_RESERVED0_MASK (0xf)

#define SYS_CPU1_INT_0_31_EN_ADDR (SOC_SYS_REG_BASE + (0x22 << 2))

#define SYS_CPU1_INT_0_31_EN_CPU1_DMA0_NSEC_INTR_EN_POS (0)
#define SYS_CPU1_INT_0_31_EN_CPU1_DMA0_NSEC_INTR_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_ENCP_SEC_INTR_EN_POS (1)
#define SYS_CPU1_INT_0_31_EN_CPU1_ENCP_SEC_INTR_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_ENCP_NSEC_INTR_EN_POS (2)
#define SYS_CPU1_INT_0_31_EN_CPU1_ENCP_NSEC_INTR_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_TIMER0_INT_EN_POS (3)
#define SYS_CPU1_INT_0_31_EN_CPU1_TIMER0_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_UART_INT_EN_POS (4)
#define SYS_CPU1_INT_0_31_EN_CPU1_UART_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_PWM0_INT_EN_POS (5)
#define SYS_CPU1_INT_0_31_EN_CPU1_PWM0_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_I2C0_INT_EN_POS (6)
#define SYS_CPU1_INT_0_31_EN_CPU1_I2C0_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_SPI0_INT_EN_POS (7)
#define SYS_CPU1_INT_0_31_EN_CPU1_SPI0_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_SADC_INT_EN_POS (8)
#define SYS_CPU1_INT_0_31_EN_CPU1_SADC_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_IRDA_INT_EN_POS (9)
#define SYS_CPU1_INT_0_31_EN_CPU1_IRDA_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_SDIO_INT_EN_POS (10)
#define SYS_CPU1_INT_0_31_EN_CPU1_SDIO_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_GDMA_INT_EN_POS (11)
#define SYS_CPU1_INT_0_31_EN_CPU1_GDMA_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_LA_INT_EN_POS (12)
#define SYS_CPU1_INT_0_31_EN_CPU1_LA_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_TIMER1_INT_EN_POS (13)
#define SYS_CPU1_INT_0_31_EN_CPU1_TIMER1_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_I2C1_INT_EN_POS (14)
#define SYS_CPU1_INT_0_31_EN_CPU1_I2C1_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_UART1_INT_EN_POS (15)
#define SYS_CPU1_INT_0_31_EN_CPU1_UART1_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_UART2_INT_EN_POS (16)
#define SYS_CPU1_INT_0_31_EN_CPU1_UART2_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_SPI1_INT_EN_POS (17)
#define SYS_CPU1_INT_0_31_EN_CPU1_SPI1_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_CAN_INT_EN_POS (18)
#define SYS_CPU1_INT_0_31_EN_CPU1_CAN_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_USB_INT_EN_POS (19)
#define SYS_CPU1_INT_0_31_EN_CPU1_USB_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_QSPI0_INT_EN_POS (20)
#define SYS_CPU1_INT_0_31_EN_CPU1_QSPI0_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_FFT_INT_EN_POS (21)
#define SYS_CPU1_INT_0_31_EN_CPU1_FFT_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_SBC_INT_EN_POS (22)
#define SYS_CPU1_INT_0_31_EN_CPU1_SBC_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_AUD_INT_EN_POS (23)
#define SYS_CPU1_INT_0_31_EN_CPU1_AUD_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_I2S0_INT_EN_POS (24)
#define SYS_CPU1_INT_0_31_EN_CPU1_I2S0_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_JPEGENC_INT_EN_POS (25)
#define SYS_CPU1_INT_0_31_EN_CPU1_JPEGENC_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_JPEGDEC_INT_EN_POS (26)
#define SYS_CPU1_INT_0_31_EN_CPU1_JPEGDEC_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_LCD_DISPLAY_INT_EN_POS (27)
#define SYS_CPU1_INT_0_31_EN_CPU1_LCD_DISPLAY_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_DMA2D_INT_EN_POS (28)
#define SYS_CPU1_INT_0_31_EN_CPU1_DMA2D_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_WIFI_INT_PHY_MPB_EN_POS (29)
#define SYS_CPU1_INT_0_31_EN_CPU1_WIFI_INT_PHY_MPB_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_WIFI_INT_PHY_RIU_EN_POS (30)
#define SYS_CPU1_INT_0_31_EN_CPU1_WIFI_INT_PHY_RIU_EN_MASK (0x1)

#define SYS_CPU1_INT_0_31_EN_CPU1_WIFI_MAC_INT_TX_RX_TIMER_EN_POS (31)
#define SYS_CPU1_INT_0_31_EN_CPU1_WIFI_MAC_INT_TX_RX_TIMER_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_ADDR (SOC_SYS_REG_BASE + (0x23 << 2))

#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_MAC_INT_TX_RX_MISC_EN_POS (0)
#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_MAC_INT_TX_RX_MISC_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_MAC_INT_RX_TRIGGER_EN_POS (1)
#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_MAC_INT_RX_TRIGGER_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_MAC_INT_TX_TRIGGER_EN_POS (2)
#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_MAC_INT_TX_TRIGGER_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_MAC_INT_PROT_TRIGGER_EN_POS (3)
#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_MAC_INT_PROT_TRIGGER_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_MAC_INT_GEN_EN_POS (4)
#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_MAC_INT_GEN_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_HSU_IRQ_EN_POS (5)
#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_HSU_IRQ_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_INT_MAC_WAKEUP_EN_POS (6)
#define SYS_CPU1_INT_32_63_EN_CPU1_WIFI_INT_MAC_WAKEUP_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_DM_IRQ_EN_POS (7)
#define SYS_CPU1_INT_32_63_EN_CPU1_DM_IRQ_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_BLE_IRQ_EN_POS (8)
#define SYS_CPU1_INT_32_63_EN_CPU1_BLE_IRQ_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_BT_IRQ_EN_POS (9)
#define SYS_CPU1_INT_32_63_EN_CPU1_BT_IRQ_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_QSPI1_INT_EN_POS (10)
#define SYS_CPU1_INT_32_63_EN_CPU1_QSPI1_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_PWM1_INT_EN_POS (11)
#define SYS_CPU1_INT_32_63_EN_CPU1_PWM1_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_I2S1_INT_EN_POS (12)
#define SYS_CPU1_INT_32_63_EN_CPU1_I2S1_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_I2S2_INT_EN_POS (13)
#define SYS_CPU1_INT_32_63_EN_CPU1_I2S2_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_H264_INT_EN_POS (14)
#define SYS_CPU1_INT_32_63_EN_CPU1_H264_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_SDMADC_INT_EN_POS (15)
#define SYS_CPU1_INT_32_63_EN_CPU1_SDMADC_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_MBOX0_INT_EN_POS (16)
#define SYS_CPU1_INT_32_63_EN_CPU1_MBOX0_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_MBOX1_INT_EN_POS (17)
#define SYS_CPU1_INT_32_63_EN_CPU1_MBOX1_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_BMC64_INT_EN_POS (18)
#define SYS_CPU1_INT_32_63_EN_CPU1_BMC64_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_DPLL_UNLOCK_INT_EN_POS (19)
#define SYS_CPU1_INT_32_63_EN_CPU1_DPLL_UNLOCK_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_TOUCHED_INT_EN_POS (20)
#define SYS_CPU1_INT_32_63_EN_CPU1_TOUCHED_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_USBPLUG_INT_EN_POS (21)
#define SYS_CPU1_INT_32_63_EN_CPU1_USBPLUG_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_RTC_INT_EN_POS (22)
#define SYS_CPU1_INT_32_63_EN_CPU1_RTC_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_GPIO_INT_EN_POS (23)
#define SYS_CPU1_INT_32_63_EN_CPU1_GPIO_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_DMA1_SEC_INT_EN_POS (24)
#define SYS_CPU1_INT_32_63_EN_CPU1_DMA1_SEC_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_DMA1_NSEC_INT_EN_POS (25)
#define SYS_CPU1_INT_32_63_EN_CPU1_DMA1_NSEC_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_YUVB_INT_EN_POS (26)
#define SYS_CPU1_INT_32_63_EN_CPU1_YUVB_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_CPU1_ROTT_INT_EN_POS (27)
#define SYS_CPU1_INT_32_63_EN_CPU1_ROTT_INT_EN_MASK (0x1)

#define SYS_CPU1_INT_32_63_EN_RESERVED0_POS (28)
#define SYS_CPU1_INT_32_63_EN_RESERVED0_MASK (0xf)

#define SYS_CPU0_INT_0_31_STATUS_ADDR (SOC_SYS_REG_BASE + (0x28 << 2))

#define SYS_CPU0_INT_0_31_STATUS_CPU0_DMA0_NSEC_INTR_ST_POS (0)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_DMA0_NSEC_INTR_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_ENCP_SEC_INTR_ST_POS (1)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_ENCP_SEC_INTR_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_ENCP_NSEC_INTR_ST_POS (2)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_ENCP_NSEC_INTR_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_TIMER0_INT_ST_POS (3)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_TIMER0_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_UART_INT_ST_POS (4)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_UART_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_PWM0_INT_ST_POS (5)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_PWM0_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_I2C0_INT_ST_POS (6)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_I2C0_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_SPI0_INT_ST_POS (7)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_SPI0_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_SADC_INT_ST_POS (8)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_SADC_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_IRDA_INT_ST_POS (9)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_IRDA_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_SDIO_INT_ST_POS (10)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_SDIO_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_GDMA_INT_ST_POS (11)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_GDMA_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_LA_INT_ST_POS (12)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_LA_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_TIMER1_INT_ST_POS (13)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_TIMER1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_I2C1_INT_ST_POS (14)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_I2C1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_UART1_INT_ST_POS (15)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_UART1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_UART2_INT_ST_POS (16)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_UART2_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_SPI1_INT_ST_POS (17)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_SPI1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_CAN_INT_ST_POS (18)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_CAN_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_USB_INT_ST_POS (19)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_USB_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_QSPI0_INT_ST_POS (20)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_QSPI0_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_FFT_INT_ST_POS (21)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_FFT_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_SBC_INT_ST_POS (22)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_SBC_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_AUD_INT_ST_POS (23)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_AUD_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_I2S0_INT_ST_POS (24)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_I2S0_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_JPEGENC_INT_ST_POS (25)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_JPEGENC_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_JPEGDEC_INT_ST_POS (26)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_JPEGDEC_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_LCD_DISPLAY_INT_ST_POS (27)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_LCD_DISPLAY_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_DMA2D_INT_ST_POS (28)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_DMA2D_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_WIFI_INT_PHY_MPB_ST_POS (29)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_WIFI_INT_PHY_MPB_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_WIFI_INT_PHY_RIU_ST_POS (30)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_WIFI_INT_PHY_RIU_ST_MASK (0x1)

#define SYS_CPU0_INT_0_31_STATUS_CPU0_WIFI_MAC_INT_TX_RX_TIMER_ST_POS (31)
#define SYS_CPU0_INT_0_31_STATUS_CPU0_WIFI_MAC_INT_TX_RX_TIMER_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_ADDR (SOC_SYS_REG_BASE + (0x29 << 2))

#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_MAC_INT_TX_RX_MISC_ST_POS (0)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_MAC_INT_TX_RX_MISC_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_MAC_INT_RX_TRIGGER_ST_POS (1)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_MAC_INT_RX_TRIGGER_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_MAC_INT_TX_TRIGGER_ST_POS (2)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_MAC_INT_TX_TRIGGER_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_MAC_INT_PROT_TRIGGER_ST_POS (3)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_MAC_INT_PROT_TRIGGER_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_MAC_INT_GEN_ST_POS (4)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_MAC_INT_GEN_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_HSU_IRQ_ST_POS (5)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_HSU_IRQ_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_INT_MAC_WAKEUP_ST_POS (6)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_WIFI_INT_MAC_WAKEUP_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_DM_IRQ_ST_POS (7)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_DM_IRQ_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_BLE_IRQ_ST_POS (8)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_BLE_IRQ_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_BT_IRQ_ST_POS (9)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_BT_IRQ_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_QSPI1_INT_ST_POS (10)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_QSPI1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_PWM1_INT_ST_POS (11)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_PWM1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_I2S1_INT_ST_POS (12)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_I2S1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_I2S2_INT_ST_POS (13)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_I2S2_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_H264_INT_ST_POS (14)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_H264_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_SDMADC_INT_ST_POS (15)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_SDMADC_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_MBOX0_INT_ST_POS (16)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_MBOX0_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_MBOX1_INT_ST_POS (17)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_MBOX1_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_BMC64_INT_ST_POS (18)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_BMC64_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_DPLL_UNLOCK_INT_ST_POS (19)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_DPLL_UNLOCK_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_TOUCHED_INT_ST_POS (20)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_TOUCHED_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_USBPLUG_INT_ST_POS (21)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_USBPLUG_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_RTC_INT_ST_POS (22)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_RTC_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_GPIO_INT_ST_POS (23)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_GPIO_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_DMA1_SEC_INT_ST_POS (24)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_DMA1_SEC_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_DMA1_NSEC_INT_ST_POS (25)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_DMA1_NSEC_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_YUVB_INT_ST_POS (26)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_YUVB_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_CPU0_ROTT_INT_ST_POS (27)
#define SYS_CPU0_INT_32_63_STATUS_CPU0_ROTT_INT_ST_MASK (0x1)

#define SYS_CPU0_INT_32_63_STATUS_RESERVED0_POS (28)
#define SYS_CPU0_INT_32_63_STATUS_RESERVED0_MASK (0xf)

#define SYS_CPU1_INT_0_31_STATUS_ADDR (SOC_SYS_REG_BASE + (0x2a << 2))

#define SYS_CPU1_INT_0_31_STATUS_CPU1_DMA0_NSEC_INTR_ST_POS (0)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_DMA0_NSEC_INTR_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_ENCP_SEC_INTR_ST_POS (1)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_ENCP_SEC_INTR_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_ENCP_NSEC_INTR_ST_POS (2)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_ENCP_NSEC_INTR_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_TIMER0_INT_ST_POS (3)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_TIMER0_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_UART_INT_ST_POS (4)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_UART_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_PWM0_INT_ST_POS (5)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_PWM0_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_I2C0_INT_ST_POS (6)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_I2C0_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_SPI0_INT_ST_POS (7)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_SPI0_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_SADC_INT_ST_POS (8)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_SADC_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_IRDA_INT_ST_POS (9)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_IRDA_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_SDIO_INT_ST_POS (10)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_SDIO_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_GDMA_INT_ST_POS (11)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_GDMA_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_LA_INT_ST_POS (12)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_LA_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_TIMER1_INT_ST_POS (13)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_TIMER1_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_I2C1_INT_ST_POS (14)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_I2C1_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_UART1_INT_ST_POS (15)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_UART1_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_UART2_INT_ST_POS (16)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_UART2_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_SPI1_INT_ST_POS (17)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_SPI1_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_CAN_INT_ST_POS (18)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_CAN_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_USB_INT_ST_POS (19)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_USB_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_QSPI0_INT_ST_POS (20)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_QSPI0_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_FFT_INT_ST_POS (21)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_FFT_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_SBC_INT_ST_POS (22)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_SBC_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_AUD_INT_ST_POS (23)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_AUD_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_I2S0_INT_ST_POS (24)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_I2S0_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_JPEGENC_INT_ST_POS (25)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_JPEGENC_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_JPEGDEC_INT_ST_POS (26)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_JPEGDEC_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_LCD_DISPLAY_INT_ST_POS (27)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_LCD_DISPLAY_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_DMA2D_INT_ST_POS (28)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_DMA2D_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_WIFI_INT_PHY_MPB_ST_POS (29)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_WIFI_INT_PHY_MPB_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_WIFI_INT_PHY_RIU_ST_POS (30)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_WIFI_INT_PHY_RIU_ST_MASK (0x1)

#define SYS_CPU1_INT_0_31_STATUS_CPU1_WIFI_MAC_INT_TX_RX_TIMER_ST_POS (31)
#define SYS_CPU1_INT_0_31_STATUS_CPU1_WIFI_MAC_INT_TX_RX_TIMER_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_ADDR (SOC_SYS_REG_BASE + (0x2b << 2))

#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_MAC_INT_TX_RX_MISC_ST_POS (0)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_MAC_INT_TX_RX_MISC_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_MAC_INT_RX_TRIGGER_ST_POS (1)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_MAC_INT_RX_TRIGGER_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_MAC_INT_TX_TRIGGER_ST_POS (2)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_MAC_INT_TX_TRIGGER_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_MAC_INT_PROT_TRIGGER_ST_POS (3)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_MAC_INT_PROT_TRIGGER_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_MAC_INT_GEN_ST_POS (4)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_MAC_INT_GEN_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_HSU_IRQ_ST_POS (5)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_HSU_IRQ_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_INT_MAC_WAKEUP_ST_POS (6)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_WIFI_INT_MAC_WAKEUP_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_DM_IRQ_ST_POS (7)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_DM_IRQ_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_BLE_IRQ_ST_POS (8)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_BLE_IRQ_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_BT_IRQ_ST_POS (9)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_BT_IRQ_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_QSPI1_INT_ST_POS (10)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_QSPI1_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_PWM1_INT_ST_POS (11)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_PWM1_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_I2S1_INT_ST_POS (12)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_I2S1_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_I2S2_INT_ST_POS (13)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_I2S2_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_H264_INT_ST_POS (14)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_H264_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_SDMADC_INT_ST_POS (15)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_SDMADC_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_MBOX0_INT_ST_POS (16)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_MBOX0_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_MBOX1_INT_ST_POS (17)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_MBOX1_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_BMC64_INT_ST_POS (18)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_BMC64_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_DPLL_UNLOCK_INT_ST_POS (19)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_DPLL_UNLOCK_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_TOUCHED_INT_ST_POS (20)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_TOUCHED_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_USBPLUG_INT_ST_POS (21)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_USBPLUG_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_RTC_INT_ST_POS (22)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_RTC_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_GPIO_INT_ST_POS (23)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_GPIO_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_DMA1_SEC_INT_ST_POS (24)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_DMA1_SEC_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_DMA1_NSEC_INT_ST_POS (25)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_DMA1_NSEC_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_YUVB_INT_ST_POS (26)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_YUVB_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_CPU1_ROTT_INT_ST_POS (27)
#define SYS_CPU1_INT_32_63_STATUS_CPU1_ROTT_INT_ST_MASK (0x1)

#define SYS_CPU1_INT_32_63_STATUS_RESERVED0_POS (28)
#define SYS_CPU1_INT_32_63_STATUS_RESERVED0_MASK (0xf)

#define SYS_GPIO_CONFIG0_ADDR (SOC_SYS_REG_BASE + (0x30 << 2))

#define SYS_GPIO_CONFIG0_GPIO_CONFIG0_POS (0)
#define SYS_GPIO_CONFIG0_GPIO_CONFIG0_MASK (0xffffffff)

#define SYS_GPIO_CONFIG1_ADDR (SOC_SYS_REG_BASE + (0x31 << 2))

#define SYS_GPIO_CONFIG1_GPIO_CONFIG1_POS (0)
#define SYS_GPIO_CONFIG1_GPIO_CONFIG1_MASK (0xffffffff)

#define SYS_GPIO_CONFIG2_ADDR (SOC_SYS_REG_BASE + (0x32 << 2))

#define SYS_GPIO_CONFIG2_GPIO_CONFIG2_POS (0)
#define SYS_GPIO_CONFIG2_GPIO_CONFIG2_MASK (0xffffffff)

#define SYS_GPIO_CONFIG3_ADDR (SOC_SYS_REG_BASE + (0x33 << 2))

#define SYS_GPIO_CONFIG3_GPIO_CONFIG3_POS (0)
#define SYS_GPIO_CONFIG3_GPIO_CONFIG3_MASK (0xffffffff)

#define SYS_GPIO_CONFIG4_ADDR (SOC_SYS_REG_BASE + (0x34 << 2))

#define SYS_GPIO_CONFIG4_GPIO_CONFIG4_POS (0)
#define SYS_GPIO_CONFIG4_GPIO_CONFIG4_MASK (0xffffffff)

#define SYS_GPIO_CONFIG5_ADDR (SOC_SYS_REG_BASE + (0x35 << 2))

#define SYS_GPIO_CONFIG5_GPIO_CONFIG5_POS (0)
#define SYS_GPIO_CONFIG5_GPIO_CONFIG5_MASK (0xffffffff)

#define SYS_SYS_DEBUG_CONFIG0_ADDR (SOC_SYS_REG_BASE + (0x38 << 2))

#define SYS_SYS_DEBUG_CONFIG0_DBUG_CONFIG0_POS (0)
#define SYS_SYS_DEBUG_CONFIG0_DBUG_CONFIG0_MASK (0xffffffff)

#define SYS_SYS_DEBUG_CONFIG1_ADDR (SOC_SYS_REG_BASE + (0x39 << 2))

#define SYS_SYS_DEBUG_CONFIG1_DBUG_CONFIG1_POS (0)
#define SYS_SYS_DEBUG_CONFIG1_DBUG_CONFIG1_MASK (0xffffffff)

#define SYS_ANA_REG0_ADDR (SOC_SYS_REG_BASE + (0x40 << 2))

#define SYS_ANA_REG0_DPLL_TSTEN_POS (0)
#define SYS_ANA_REG0_DPLL_TSTEN_MASK (0x1)

#define SYS_ANA_REG0_CP_POS (1)
#define SYS_ANA_REG0_CP_MASK (0x7)

#define SYS_ANA_REG0_SPIDETEN_POS (4)
#define SYS_ANA_REG0_SPIDETEN_MASK (0x1)

#define SYS_ANA_REG0_HVREF_POS (5)
#define SYS_ANA_REG0_HVREF_MASK (0x3)

#define SYS_ANA_REG0_LVREF_POS (7)
#define SYS_ANA_REG0_LVREF_MASK (0x3)

#define SYS_ANA_REG0_RZCTRL26M_POS (9)
#define SYS_ANA_REG0_RZCTRL26M_MASK (0x1)

#define SYS_ANA_REG0_LOOPRZCTRL_POS (10)
#define SYS_ANA_REG0_LOOPRZCTRL_MASK (0xf)

#define SYS_ANA_REG0_RPC_POS (14)
#define SYS_ANA_REG0_RPC_MASK (0x3)

#define SYS_ANA_REG0_OPENLOOP_EN_POS (16)
#define SYS_ANA_REG0_OPENLOOP_EN_MASK (0x1)

#define SYS_ANA_REG0_CKSEL_POS (17)
#define SYS_ANA_REG0_CKSEL_MASK (0x3)

#define SYS_ANA_REG0_SPITRIG_POS (19)
#define SYS_ANA_REG0_SPITRIG_MASK (0x1)

#define SYS_ANA_REG0_BAND0_POS (20)
#define SYS_ANA_REG0_BAND0_MASK (0x1)

#define SYS_ANA_REG0_BAND1_POS (21)
#define SYS_ANA_REG0_BAND1_MASK (0x1)

#define SYS_ANA_REG0_BAND_POS (22)
#define SYS_ANA_REG0_BAND_MASK (0x7)

#define SYS_ANA_REG0_BANDMANUAL_POS (25)
#define SYS_ANA_REG0_BANDMANUAL_MASK (0x1)

#define SYS_ANA_REG0_DSPTRIG_POS (26)
#define SYS_ANA_REG0_DSPTRIG_MASK (0x1)

#define SYS_ANA_REG0_LPEN_DPLL_POS (27)
#define SYS_ANA_REG0_LPEN_DPLL_MASK (0x1)

#define SYS_ANA_REG0_NC_28_30_POS (28)
#define SYS_ANA_REG0_NC_28_30_MASK (0x7)

#define SYS_ANA_REG0_VCTRL_DPLLLDO_POS (31)
#define SYS_ANA_REG0_VCTRL_DPLLLDO_MASK (0x1)

#define SYS_ANA_REG1_ADDR (SOC_SYS_REG_BASE + (0x41 << 2))

#define SYS_ANA_REG1_NC3_POS (0)
#define SYS_ANA_REG1_NC3_MASK (0x1)

#define SYS_ANA_REG1_NC2_POS (1)
#define SYS_ANA_REG1_NC2_MASK (0x1)

#define SYS_ANA_REG1_MSW_POS (2)
#define SYS_ANA_REG1_MSW_MASK (0x1ff)

#define SYS_ANA_REG1_ICTRL_POS (11)
#define SYS_ANA_REG1_ICTRL_MASK (0x7)

#define SYS_ANA_REG1_OSC_TRIG_POS (14)
#define SYS_ANA_REG1_OSC_TRIG_MASK (0x1)

#define SYS_ANA_REG1_OSCCAL_TRIG_POS (15)
#define SYS_ANA_REG1_OSCCAL_TRIG_MASK (0x1)

#define SYS_ANA_REG1_CNTI_POS (16)
#define SYS_ANA_REG1_CNTI_MASK (0x1ff)

#define SYS_ANA_REG1_SPI_RST_POS (25)
#define SYS_ANA_REG1_SPI_RST_MASK (0x1)

#define SYS_ANA_REG1_AMSEL_POS (26)
#define SYS_ANA_REG1_AMSEL_MASK (0x1)

#define SYS_ANA_REG1_DIVCTRL_POS (27)
#define SYS_ANA_REG1_DIVCTRL_MASK (0x7)

#define SYS_ANA_REG1_NC1_POS (30)
#define SYS_ANA_REG1_NC1_MASK (0x1)

#define SYS_ANA_REG1_NC0_POS (31)
#define SYS_ANA_REG1_NC0_MASK (0x1)

#define SYS_ANA_REG2_ADDR (SOC_SYS_REG_BASE + (0x42 << 2))

#define SYS_ANA_REG2_XTALH_CTUNE_POS (0)
#define SYS_ANA_REG2_XTALH_CTUNE_MASK (0xff)

#define SYS_ANA_REG2_FORCE_26MPLL_POS (8)
#define SYS_ANA_REG2_FORCE_26MPLL_MASK (0x1)

#define SYS_ANA_REG2_GADC_CMP_ICTRL_POS (9)
#define SYS_ANA_REG2_GADC_CMP_ICTRL_MASK (0x3)

#define SYS_ANA_REG2_GADC_INBUF_ICTRL_POS (11)
#define SYS_ANA_REG2_GADC_INBUF_ICTRL_MASK (0x3)

#define SYS_ANA_REG2_GADC_REFBUF_ICTRL_POS (13)
#define SYS_ANA_REG2_GADC_REFBUF_ICTRL_MASK (0x3)

#define SYS_ANA_REG2_GADC_NOBUF_ENABLE_POS (15)
#define SYS_ANA_REG2_GADC_NOBUF_ENABLE_MASK (0x1)

#define SYS_ANA_REG2_VREF_SCALE_POS (16)
#define SYS_ANA_REG2_VREF_SCALE_MASK (0x1)

#define SYS_ANA_REG2_SCAL_EN_POS (17)
#define SYS_ANA_REG2_SCAL_EN_MASK (0x1)

#define SYS_ANA_REG2_GADC_CAPCAL_EN_POS (18)
#define SYS_ANA_REG2_GADC_CAPCAL_EN_MASK (0x1)

#define SYS_ANA_REG2_GADC_CAPCAL_POS (19)
#define SYS_ANA_REG2_GADC_CAPCAL_MASK (0x3f)

#define SYS_ANA_REG2_SP_NT_CTRL_POS (25)
#define SYS_ANA_REG2_SP_NT_CTRL_MASK (0x7f)

#define SYS_ANA_REG3_ADDR (SOC_SYS_REG_BASE + (0x43 << 2))

#define SYS_ANA_REG3_USBPEN_POS (0)
#define SYS_ANA_REG3_USBPEN_MASK (0xf)

#define SYS_ANA_REG3_USBNEN_POS (4)
#define SYS_ANA_REG3_USBNEN_MASK (0xf)

#define SYS_ANA_REG3_HPSSREN_POS (8)
#define SYS_ANA_REG3_HPSSREN_MASK (0x1)

#define SYS_ANA_REG3_CK_SEL_POS (9)
#define SYS_ANA_REG3_CK_SEL_MASK (0x1)

#define SYS_ANA_REG3_ANABUF_SEL_RX_POS (10)
#define SYS_ANA_REG3_ANABUF_SEL_RX_MASK (0x1)

#define SYS_ANA_REG3_PWD_XTALLDO_POS (11)
#define SYS_ANA_REG3_PWD_XTALLDO_MASK (0x1)

#define SYS_ANA_REG3_IAMP_POS (12)
#define SYS_ANA_REG3_IAMP_MASK (0x1)

#define SYS_ANA_REG3_VDDREN_POS (13)
#define SYS_ANA_REG3_VDDREN_MASK (0x1)

#define SYS_ANA_REG3_XAMP_POS (14)
#define SYS_ANA_REG3_XAMP_MASK (0x3f)

#define SYS_ANA_REG3_VOSEL_POS (20)
#define SYS_ANA_REG3_VOSEL_MASK (0x1f)

#define SYS_ANA_REG3_EN_XTALH_SLEEP_POS (25)
#define SYS_ANA_REG3_EN_XTALH_SLEEP_MASK (0x1)

#define SYS_ANA_REG3_XTAL40_EN_POS (26)
#define SYS_ANA_REG3_XTAL40_EN_MASK (0x1)

#define SYS_ANA_REG3_BUFICTRL_POS (27)
#define SYS_ANA_REG3_BUFICTRL_MASK (0x1)

#define SYS_ANA_REG3_IBIAS_CTRL_POS (28)
#define SYS_ANA_REG3_IBIAS_CTRL_MASK (0x3)

#define SYS_ANA_REG3_ICORE_CTRL_POS (30)
#define SYS_ANA_REG3_ICORE_CTRL_MASK (0x3)

#define SYS_ANA_REG4_ADDR (SOC_SYS_REG_BASE + (0x44 << 2))

#define SYS_ANA_REG4_ANABUF_SEL_TX_POS (0)
#define SYS_ANA_REG4_ANABUF_SEL_TX_MASK (0x1)

#define SYS_ANA_REG4_TRNG_TSTEN_POS (1)
#define SYS_ANA_REG4_TRNG_TSTEN_MASK (0x1)

#define SYS_ANA_REG4_ITUNE_REF_POS (2)
#define SYS_ANA_REG4_ITUNE_REF_MASK (0x7)

#define SYS_ANA_REG4_ITUNE_OPA_POS (5)
#define SYS_ANA_REG4_ITUNE_OPA_MASK (0x7)

#define SYS_ANA_REG4_ITUNE_CMP_POS (8)
#define SYS_ANA_REG4_ITUNE_CMP_MASK (0x7)

#define SYS_ANA_REG4_RNOOISE_SEL_POS (11)
#define SYS_ANA_REG4_RNOOISE_SEL_MASK (0x1)

#define SYS_ANA_REG4_FSLOW_SEL_POS (12)
#define SYS_ANA_REG4_FSLOW_SEL_MASK (0x7)

#define SYS_ANA_REG4_FFAST_SEL_POS (15)
#define SYS_ANA_REG4_FFAST_SEL_MASK (0xf)

#define SYS_ANA_REG4_TRNG_TSTCK_SEL_POS (19)
#define SYS_ANA_REG4_TRNG_TSTCK_SEL_MASK (0x1)

#define SYS_ANA_REG4_CKTST_SEL_POS (20)
#define SYS_ANA_REG4_CKTST_SEL_MASK (0x3)

#define SYS_ANA_REG4_CK_TST_ENBALE_POS (22)
#define SYS_ANA_REG4_CK_TST_ENBALE_MASK (0x1)

#define SYS_ANA_REG4_SW_BIAS_POS (23)
#define SYS_ANA_REG4_SW_BIAS_MASK (0x1)

#define SYS_ANA_REG4_CRB_POS (24)
#define SYS_ANA_REG4_CRB_MASK (0xf)

#define SYS_ANA_REG4_PORT_ENABLEL_POS (28)
#define SYS_ANA_REG4_PORT_ENABLEL_MASK (0xf)

#define SYS_ANA_REG5_ADDR (SOC_SYS_REG_BASE + (0x45 << 2))

#define SYS_ANA_REG5_EN_USB_POS (0)
#define SYS_ANA_REG5_EN_USB_MASK (0x1)

#define SYS_ANA_REG5_EN_XTALL_POS (1)
#define SYS_ANA_REG5_EN_XTALL_MASK (0x1)

#define SYS_ANA_REG5_EN_DCO_POS (2)
#define SYS_ANA_REG5_EN_DCO_MASK (0x1)

#define SYS_ANA_REG5_EN_RAM_POS (3)
#define SYS_ANA_REG5_EN_RAM_MASK (0x1)

#define SYS_ANA_REG5_EN_TEMP_POS (4)
#define SYS_ANA_REG5_EN_TEMP_MASK (0x1)

#define SYS_ANA_REG5_EN_DPLL_POS (5)
#define SYS_ANA_REG5_EN_DPLL_MASK (0x1)

#define SYS_ANA_REG5_EN_CB_POS (6)
#define SYS_ANA_REG5_EN_CB_MASK (0x1)

#define SYS_ANA_REG5_EN_LCD_POS (7)
#define SYS_ANA_REG5_EN_LCD_MASK (0x1)

#define SYS_ANA_REG5_TRXSPI_CTRL_POS (8)
#define SYS_ANA_REG5_TRXSPI_CTRL_MASK (0x3)

#define SYS_ANA_REG5_ADC_DIV_POS (10)
#define SYS_ANA_REG5_ADC_DIV_MASK (0x3)

#define SYS_ANA_REG5_USB_SPEED_POS (12)
#define SYS_ANA_REG5_USB_SPEED_MASK (0x1)

#define SYS_ANA_REG5_SPIDEEPSLEEP_POS (13)
#define SYS_ANA_REG5_SPIDEEPSLEEP_MASK (0x1)

#define SYS_ANA_REG5_VSEL_POS (14)
#define SYS_ANA_REG5_VSEL_MASK (0x1)

#define SYS_ANA_REG5_SWB_POS (15)
#define SYS_ANA_REG5_SWB_MASK (0x1)

#define SYS_ANA_REG5_ITUNE_XTALL_POS (16)
#define SYS_ANA_REG5_ITUNE_XTALL_MASK (0xf)

#define SYS_ANA_REG5_XTALL_TEN_POS (20)
#define SYS_ANA_REG5_XTALL_TEN_MASK (0x1)

#define SYS_ANA_REG5_ROSC_TSTEN_POS (21)
#define SYS_ANA_REG5_ROSC_TSTEN_MASK (0x1)

#define SYS_ANA_REG5_BCAL_START_POS (22)
#define SYS_ANA_REG5_BCAL_START_MASK (0x1)

#define SYS_ANA_REG5_BCAL_EN_POS (23)
#define SYS_ANA_REG5_BCAL_EN_MASK (0x1)

#define SYS_ANA_REG5_BCAL_SEL_POS (24)
#define SYS_ANA_REG5_BCAL_SEL_MASK (0x7)

#define SYS_ANA_REG5_VBIAS_POS (27)
#define SYS_ANA_REG5_VBIAS_MASK (0x1f)

#define SYS_ANA_REG6_ADDR (SOC_SYS_REG_BASE + (0x46 << 2))

#define SYS_ANA_REG6_CALIB_INTERVAL_POS (0)
#define SYS_ANA_REG6_CALIB_INTERVAL_MASK (0x3ff)

#define SYS_ANA_REG6_MODIFY_INTERVAL_POS (10)
#define SYS_ANA_REG6_MODIFY_INTERVAL_MASK (0x3f)

#define SYS_ANA_REG6_XTAL_WAKEUP_TIME_POS (16)
#define SYS_ANA_REG6_XTAL_WAKEUP_TIME_MASK (0xf)

#define SYS_ANA_REG6_SPI_TRIG_POS (20)
#define SYS_ANA_REG6_SPI_TRIG_MASK (0x1)

#define SYS_ANA_REG6_MODIFI_AUTO_POS (21)
#define SYS_ANA_REG6_MODIFI_AUTO_MASK (0x1)

#define SYS_ANA_REG6_CALIB_AUTO_POS (22)
#define SYS_ANA_REG6_CALIB_AUTO_MASK (0x1)

#define SYS_ANA_REG6_CAL_MODE_POS (23)
#define SYS_ANA_REG6_CAL_MODE_MASK (0x1)

#define SYS_ANA_REG6_MANU_ENA_POS (24)
#define SYS_ANA_REG6_MANU_ENA_MASK (0x1)

#define SYS_ANA_REG6_MANU_CIN_POS (25)
#define SYS_ANA_REG6_MANU_CIN_MASK (0x7f)

#define SYS_ANA_REG7_ADDR (SOC_SYS_REG_BASE + (0x47 << 2))

#define SYS_ANA_REG7_PORT_ENABLEL_POS (0)
#define SYS_ANA_REG7_PORT_ENABLEL_MASK (0xffffffff)

#define SYS_ANA_REG8_ADDR (SOC_SYS_REG_BASE + (0x48 << 2))

#define SYS_ANA_REG8_IOLDO_LP_POS (0)
#define SYS_ANA_REG8_IOLDO_LP_MASK (0x1)

#define SYS_ANA_REG8_CORELDO_HP_POS (1)
#define SYS_ANA_REG8_CORELDO_HP_MASK (0x1)

#define SYS_ANA_REG8_DLDOHP_POS (2)
#define SYS_ANA_REG8_DLDOHP_MASK (0x1)

#define SYS_ANA_REG8_T_VANALDOSEL_POS (3)
#define SYS_ANA_REG8_T_VANALDOSEL_MASK (0x7)

#define SYS_ANA_REG8_R_VANALDOSEL_POS (6)
#define SYS_ANA_REG8_R_VANALDOSEL_MASK (0x7)

#define SYS_ANA_REG8_EN_TRSW_POS (9)
#define SYS_ANA_REG8_EN_TRSW_MASK (0x1)

#define SYS_ANA_REG8_ALDOHP_POS (10)
#define SYS_ANA_REG8_ALDOHP_MASK (0x1)

#define SYS_ANA_REG8_ANACURLIM_POS (11)
#define SYS_ANA_REG8_ANACURLIM_MASK (0x1)

#define SYS_ANA_REG8_VIOLDOSEL_POS (12)
#define SYS_ANA_REG8_VIOLDOSEL_MASK (0x7)

#define SYS_ANA_REG8_IOCURLIM_POS (15)
#define SYS_ANA_REG8_IOCURLIM_MASK (0x1)

#define SYS_ANA_REG8_VALOLDOSEL_POS (16)
#define SYS_ANA_REG8_VALOLDOSEL_MASK (0x7)

#define SYS_ANA_REG8_ALOPOWSEL_POS (19)
#define SYS_ANA_REG8_ALOPOWSEL_MASK (0x1)

#define SYS_ANA_REG8_EN_FAST_ALOLDO_POS (20)
#define SYS_ANA_REG8_EN_FAST_ALOLDO_MASK (0x1)

#define SYS_ANA_REG8_ALOLDOHP_POS (21)
#define SYS_ANA_REG8_ALOLDOHP_MASK (0x1)

#define SYS_ANA_REG8_BGCAL_POS (22)
#define SYS_ANA_REG8_BGCAL_MASK (0x3f)

#define SYS_ANA_REG8_VBGCALMODE_POS (28)
#define SYS_ANA_REG8_VBGCALMODE_MASK (0x1)

#define SYS_ANA_REG8_VBGCALSTART_POS (29)
#define SYS_ANA_REG8_VBGCALSTART_MASK (0x1)

#define SYS_ANA_REG8_PWD_BGCAL_POS (30)
#define SYS_ANA_REG8_PWD_BGCAL_MASK (0x1)

#define SYS_ANA_REG8_SPI_ENVBG_POS (31)
#define SYS_ANA_REG8_SPI_ENVBG_MASK (0x1)

#define SYS_ANA_REG9_ADDR (SOC_SYS_REG_BASE + (0x49 << 2))

#define SYS_ANA_REG9_WKGPIOSEL1_POS (0)
#define SYS_ANA_REG9_WKGPIOSEL1_MASK (0xf)

#define SYS_ANA_REG9_RST_WKS1V_POS (4)
#define SYS_ANA_REG9_RST_WKS1V_MASK (0x1)

#define SYS_ANA_REG9_WKGPIOSEL2_POS (5)
#define SYS_ANA_REG9_WKGPIOSEL2_MASK (0xf)

#define SYS_ANA_REG9_SPI_LATCH1V_POS (9)
#define SYS_ANA_REG9_SPI_LATCH1V_MASK (0x1)

#define SYS_ANA_REG9_DIGCURLIM_POS (10)
#define SYS_ANA_REG9_DIGCURLIM_MASK (0x1)

#define SYS_ANA_REG9_PUPRES_ENB1V_POS (11)
#define SYS_ANA_REG9_PUPRES_ENB1V_MASK (0x1)

#define SYS_ANA_REG9_PDNRES_EN1V_POS (12)
#define SYS_ANA_REG9_PDNRES_EN1V_MASK (0x1)

#define SYS_ANA_REG9_D_VEASEL1V_POS (13)
#define SYS_ANA_REG9_D_VEASEL1V_MASK (0x3)

#define SYS_ANA_REG9_ENSFSDD_POS (15)
#define SYS_ANA_REG9_ENSFSDD_MASK (0x1)

#define SYS_ANA_REG9_VCOREHSEL_POS (16)
#define SYS_ANA_REG9_VCOREHSEL_MASK (0xf)

#define SYS_ANA_REG9_VCORELSEL_POS (20)
#define SYS_ANA_REG9_VCORELSEL_MASK (0x7)

#define SYS_ANA_REG9_VLDEN_POS (23)
#define SYS_ANA_REG9_VLDEN_MASK (0x1)

#define SYS_ANA_REG9_EN_FAST_CORELDO_POS (24)
#define SYS_ANA_REG9_EN_FAST_CORELDO_MASK (0x1)

#define SYS_ANA_REG9_PWDCORELDO_POS (25)
#define SYS_ANA_REG9_PWDCORELDO_MASK (0x1)

#define SYS_ANA_REG9_VDIGHSEL_POS (26)
#define SYS_ANA_REG9_VDIGHSEL_MASK (0x7)

#define SYS_ANA_REG9_VDIGSEL_POS (29)
#define SYS_ANA_REG9_VDIGSEL_MASK (0x3)

#define SYS_ANA_REG9_VDD12LDEN_POS (31)
#define SYS_ANA_REG9_VDD12LDEN_MASK (0x1)

#define SYS_ANA_REG10_ADDR (SOC_SYS_REG_BASE + (0x4a << 2))

#define SYS_ANA_REG10_PASOFT_ST_POS (0)
#define SYS_ANA_REG10_PASOFT_ST_MASK (0xf)

#define SYS_ANA_REG10_AZCDCNT_MANU_POS (4)
#define SYS_ANA_REG10_AZCDCNT_MANU_MASK (0x7)

#define SYS_ANA_REG10_TIMER_SEL_POS (7)
#define SYS_ANA_REG10_TIMER_SEL_MASK (0xf)

#define SYS_ANA_REG10_VPABUCKSEL_POS (11)
#define SYS_ANA_REG10_VPABUCKSEL_MASK (0xf)

#define SYS_ANA_REG10_SPI_TIMERWKEN_POS (15)
#define SYS_ANA_REG10_SPI_TIMERWKEN_MASK (0x1)

#define SYS_ANA_REG10_NC_16_16_POS (16)
#define SYS_ANA_REG10_NC_16_16_MASK (0x1)

#define SYS_ANA_REG10_SD_POS (17)
#define SYS_ANA_REG10_SD_MASK (0x1)

#define SYS_ANA_REG10_IOLDOSEL_POS (18)
#define SYS_ANA_REG10_IOLDOSEL_MASK (0x1)

#define SYS_ANA_REG10_IOBYAPSSEN_POS (19)
#define SYS_ANA_REG10_IOBYAPSSEN_MASK (0x1)

#define SYS_ANA_REG10_CKFS_POS (20)
#define SYS_ANA_REG10_CKFS_MASK (0x3)

#define SYS_ANA_REG10_CKINTSEL_POS (22)
#define SYS_ANA_REG10_CKINTSEL_MASK (0x1)

#define SYS_ANA_REG10_OSCCALTRIG_POS (23)
#define SYS_ANA_REG10_OSCCALTRIG_MASK (0x1)

#define SYS_ANA_REG10_MROSCSEL_POS (24)
#define SYS_ANA_REG10_MROSCSEL_MASK (0x1)

#define SYS_ANA_REG10_MROSCI_CAL_POS (25)
#define SYS_ANA_REG10_MROSCI_CAL_MASK (0x7)

#define SYS_ANA_REG10_MROSCCAP_CAL_POS (28)
#define SYS_ANA_REG10_MROSCCAP_CAL_MASK (0xf)

#define SYS_ANA_REG11_ADDR (SOC_SYS_REG_BASE + (0x4b << 2))

#define SYS_ANA_REG11_SFSR_POS (0)
#define SYS_ANA_REG11_SFSR_MASK (0xf)

#define SYS_ANA_REG11_ENSFSAA_POS (4)
#define SYS_ANA_REG11_ENSFSAA_MASK (0x1)

#define SYS_ANA_REG11_APFMS_POS (5)
#define SYS_ANA_REG11_APFMS_MASK (0x1f)

#define SYS_ANA_REG11_ATMPO_SEL_POS (10)
#define SYS_ANA_REG11_ATMPO_SEL_MASK (0x3)

#define SYS_ANA_REG11_AMPOEN_POS (12)
#define SYS_ANA_REG11_AMPOEN_MASK (0x1)

#define SYS_ANA_REG11_ENPOWA_POS (13)
#define SYS_ANA_REG11_ENPOWA_MASK (0x1)

#define SYS_ANA_REG11_AVEA_SEL_POS (14)
#define SYS_ANA_REG11_AVEA_SEL_MASK (0x3)

#define SYS_ANA_REG11_AFORCEPFM_POS (16)
#define SYS_ANA_REG11_AFORCEPFM_MASK (0x1)

#define SYS_ANA_REG11_ACLS_POS (17)
#define SYS_ANA_REG11_ACLS_MASK (0x7)

#define SYS_ANA_REG11_ASWRSTEN_POS (20)
#define SYS_ANA_REG11_ASWRSTEN_MASK (0x1)

#define SYS_ANA_REG11_ARIPC_POS (21)
#define SYS_ANA_REG11_ARIPC_MASK (0x7)

#define SYS_ANA_REG11_ARAMPC_POS (24)
#define SYS_ANA_REG11_ARAMPC_MASK (0xf)

#define SYS_ANA_REG11_ARAMPCEN_POS (28)
#define SYS_ANA_REG11_ARAMPCEN_MASK (0x1)

#define SYS_ANA_REG11_AENBURST_POS (29)
#define SYS_ANA_REG11_AENBURST_MASK (0x1)

#define SYS_ANA_REG11_APFMEN_POS (30)
#define SYS_ANA_REG11_APFMEN_MASK (0x1)

#define SYS_ANA_REG11_ALDOSEL_POS (31)
#define SYS_ANA_REG11_ALDOSEL_MASK (0x1)

#define SYS_ANA_REG12_ADDR (SOC_SYS_REG_BASE + (0x4c << 2))

#define SYS_ANA_REG12_BUCKD_SOFTST_POS (0)
#define SYS_ANA_REG12_BUCKD_SOFTST_MASK (0xf)

#define SYS_ANA_REG12_DZCDCNT_MANU_POS (4)
#define SYS_ANA_REG12_DZCDCNT_MANU_MASK (0x7)

#define SYS_ANA_REG12_CLK_SEL_POS (7)
#define SYS_ANA_REG12_CLK_SEL_MASK (0x1)

#define SYS_ANA_REG12_DPFMS_POS (8)
#define SYS_ANA_REG12_DPFMS_MASK (0x1f)

#define SYS_ANA_REG12_DTMPO_SEL_POS (13)
#define SYS_ANA_REG12_DTMPO_SEL_MASK (0x3)

#define SYS_ANA_REG12_DMPOEN_POS (15)
#define SYS_ANA_REG12_DMPOEN_MASK (0x1)

#define SYS_ANA_REG12_DFORCEPFM_POS (16)
#define SYS_ANA_REG12_DFORCEPFM_MASK (0x1)

#define SYS_ANA_REG12_DCLS_POS (17)
#define SYS_ANA_REG12_DCLS_MASK (0x7)

#define SYS_ANA_REG12_DSWRSTEN_POS (20)
#define SYS_ANA_REG12_DSWRSTEN_MASK (0x1)

#define SYS_ANA_REG12_DRIPC_POS (21)
#define SYS_ANA_REG12_DRIPC_MASK (0x7)

#define SYS_ANA_REG12_DRAMPC_POS (24)
#define SYS_ANA_REG12_DRAMPC_MASK (0xf)

#define SYS_ANA_REG12_DRAMPCEN_POS (28)
#define SYS_ANA_REG12_DRAMPCEN_MASK (0x1)

#define SYS_ANA_REG12_DENBURST_POS (29)
#define SYS_ANA_REG12_DENBURST_MASK (0x1)

#define SYS_ANA_REG12_DPFMEN_POS (30)
#define SYS_ANA_REG12_DPFMEN_MASK (0x1)

#define SYS_ANA_REG12_DLDOSEL_POS (31)
#define SYS_ANA_REG12_DLDOSEL_MASK (0x1)

#define SYS_ANA_REG13_ADDR (SOC_SYS_REG_BASE + (0x4d << 2))

#define SYS_ANA_REG13_PWDOVP1V_POS (0)
#define SYS_ANA_REG13_PWDOVP1V_MASK (0x1)

#define SYS_ANA_REG13_ASOFT_STC_POS (1)
#define SYS_ANA_REG13_ASOFT_STC_MASK (0xf)

#define SYS_ANA_REG13_VOLEN_POS (5)
#define SYS_ANA_REG13_VOLEN_MASK (0x1)

#define SYS_ANA_REG13_DPFMS_POS (6)
#define SYS_ANA_REG13_DPFMS_MASK (0x1f)

#define SYS_ANA_REG13_DTMPO_SEL_POS (11)
#define SYS_ANA_REG13_DTMPO_SEL_MASK (0x3)

#define SYS_ANA_REG13_DMPOEN_POS (13)
#define SYS_ANA_REG13_DMPOEN_MASK (0x1)

#define SYS_ANA_REG13_PAVEA_SEL_POS (14)
#define SYS_ANA_REG13_PAVEA_SEL_MASK (0x3)

#define SYS_ANA_REG13_DFORCEPFM_POS (16)
#define SYS_ANA_REG13_DFORCEPFM_MASK (0x1)

#define SYS_ANA_REG13_DCLS_POS (17)
#define SYS_ANA_REG13_DCLS_MASK (0x7)

#define SYS_ANA_REG13_DSWRSTEN_POS (20)
#define SYS_ANA_REG13_DSWRSTEN_MASK (0x1)

#define SYS_ANA_REG13_DRIPC_POS (21)
#define SYS_ANA_REG13_DRIPC_MASK (0x7)

#define SYS_ANA_REG13_DRAMPC_POS (24)
#define SYS_ANA_REG13_DRAMPC_MASK (0xf)

#define SYS_ANA_REG13_DRAMPCEN_POS (28)
#define SYS_ANA_REG13_DRAMPCEN_MASK (0x1)

#define SYS_ANA_REG13_PAENBURST_POS (29)
#define SYS_ANA_REG13_PAENBURST_MASK (0x1)

#define SYS_ANA_REG13_PAPFMEN_POS (30)
#define SYS_ANA_REG13_PAPFMEN_MASK (0x1)

#define SYS_ANA_REG13_ENBUCKPA_POS (31)
#define SYS_ANA_REG13_ENBUCKPA_MASK (0x1)

#define SYS_ANA_REG14_ADDR (SOC_SYS_REG_BASE + (0x4e << 2))

#define SYS_ANA_REG14_CHS_POS (0)
#define SYS_ANA_REG14_CHS_MASK (0xffff)

#define SYS_ANA_REG14_EN_LPMOD_POS (16)
#define SYS_ANA_REG14_EN_LPMOD_MASK (0x1)

#define SYS_ANA_REG14_CAL_VTH_POS (17)
#define SYS_ANA_REG14_CAL_VTH_MASK (0x7)

#define SYS_ANA_REG14_CRG_POS (20)
#define SYS_ANA_REG14_CRG_MASK (0x3)

#define SYS_ANA_REG14_VREFS_POS (22)
#define SYS_ANA_REG14_VREFS_MASK (0xf)

#define SYS_ANA_REG14_GAIN_S_POS (26)
#define SYS_ANA_REG14_GAIN_S_MASK (0xf)

#define SYS_ANA_REG14_TD_LATCH1V_POS (30)
#define SYS_ANA_REG14_TD_LATCH1V_MASK (0x1)

#define SYS_ANA_REG14_PWD_TD_POS (31)
#define SYS_ANA_REG14_PWD_TD_MASK (0x1)

#define SYS_ANA_REG15_ADDR (SOC_SYS_REG_BASE + (0x4f << 2))

#define SYS_ANA_REG15_CAL_NUMBER1V_POS (0)
#define SYS_ANA_REG15_CAL_NUMBER1V_MASK (0xf)

#define SYS_ANA_REG15_CAL_PERIOD1V_POS (4)
#define SYS_ANA_REG15_CAL_PERIOD1V_MASK (0x1ff)

#define SYS_ANA_REG15_TEST_NUMBER1V_POS (13)
#define SYS_ANA_REG15_TEST_NUMBER1V_MASK (0xf)

#define SYS_ANA_REG15_TEST_PERIOD1V_POS (17)
#define SYS_ANA_REG15_TEST_PERIOD1V_MASK (0xf)

#define SYS_ANA_REG15_NC_21_21_POS (21)
#define SYS_ANA_REG15_NC_21_21_MASK (0x1)

#define SYS_ANA_REG15_CHS_SEL_CAL1V_POS (22)
#define SYS_ANA_REG15_CHS_SEL_CAL1V_MASK (0xf)

#define SYS_ANA_REG15_CAL_DONE_CLR1V_POS (26)
#define SYS_ANA_REG15_CAL_DONE_CLR1V_MASK (0x1)

#define SYS_ANA_REG15_EN_CAL_FORCE1V_POS (27)
#define SYS_ANA_REG15_EN_CAL_FORCE1V_MASK (0x1)

#define SYS_ANA_REG15_EN_CAL_AUTO1V_POS (28)
#define SYS_ANA_REG15_EN_CAL_AUTO1V_MASK (0x1)

#define SYS_ANA_REG15_EN_SCM_POS (29)
#define SYS_ANA_REG15_EN_SCM_MASK (0x1)

#define SYS_ANA_REG15_EN_ADCMOD_POS (30)
#define SYS_ANA_REG15_EN_ADCMOD_MASK (0x1)

#define SYS_ANA_REG15_ENFSR1V_POS (31)
#define SYS_ANA_REG15_ENFSR1V_MASK (0x1)

#define SYS_ANA_REG16_ADDR (SOC_SYS_REG_BASE + (0x50 << 2))

#define SYS_ANA_REG16_INT_EN_POS (0)
#define SYS_ANA_REG16_INT_EN_MASK (0x3ff)

#define SYS_ANA_REG16_INT_EN16_POS (10)
#define SYS_ANA_REG16_INT_EN16_MASK (0x1)

#define SYS_ANA_REG16_NC_11_15_POS (11)
#define SYS_ANA_REG16_NC_11_15_MASK (0x1f)

#define SYS_ANA_REG16_CKADC_SEL_POS (16)
#define SYS_ANA_REG16_CKADC_SEL_MASK (0x1)

#define SYS_ANA_REG16_INT_CLR_SEL1V_POS (17)
#define SYS_ANA_REG16_INT_CLR_SEL1V_MASK (0x1)

#define SYS_ANA_REG16_CTRL_CK2D_POS (18)
#define SYS_ANA_REG16_CTRL_CK2D_MASK (0x1)

#define SYS_ANA_REG16_CTRL_SERI_CAP_POS (19)
#define SYS_ANA_REG16_CTRL_SERI_CAP_MASK (0x1)

#define SYS_ANA_REG16_EN_TESTCMP1V_POS (20)
#define SYS_ANA_REG16_EN_TESTCMP1V_MASK (0x1)

#define SYS_ANA_REG16_EN_MAN_WR1V_POS (21)
#define SYS_ANA_REG16_EN_MAN_WR1V_MASK (0x1)

#define SYS_ANA_REG16_EN_MANMOD1V_POS (22)
#define SYS_ANA_REG16_EN_MANMOD1V_MASK (0x1)

#define SYS_ANA_REG16_CAP_CALSPI1V_POS (23)
#define SYS_ANA_REG16_CAP_CALSPI1V_MASK (0x1ff)

#define SYS_ANA_REG17_ADDR (SOC_SYS_REG_BASE + (0x51 << 2))

#define SYS_ANA_REG17_INT_CLR_POS (0)
#define SYS_ANA_REG17_INT_CLR_MASK (0x3ff)

#define SYS_ANA_REG17_INT_CLR16_POS (10)
#define SYS_ANA_REG17_INT_CLR16_MASK (0x1)

#define SYS_ANA_REG17_NC_11_11_POS (11)
#define SYS_ANA_REG17_NC_11_11_MASK (0x1)

#define SYS_ANA_REG17_INT_CLR_CAL_POS (12)
#define SYS_ANA_REG17_INT_CLR_CAL_MASK (0x3ff)

#define SYS_ANA_REG17_INT_EN_CAL_POS (22)
#define SYS_ANA_REG17_INT_EN_CAL_MASK (0x3ff)

#define SYS_ANA_REG18_ADDR (SOC_SYS_REG_BASE + (0x52 << 2))

#define SYS_ANA_REG18_ISELAUD_POS (0)
#define SYS_ANA_REG18_ISELAUD_MASK (0x1)

#define SYS_ANA_REG18_AUDCK_RLCEN1V_POS (1)
#define SYS_ANA_REG18_AUDCK_RLCEN1V_MASK (0x1)

#define SYS_ANA_REG18_LCHCKINVEN1V_POS (2)
#define SYS_ANA_REG18_LCHCKINVEN1V_MASK (0x1)

#define SYS_ANA_REG18_ENAUDBIAS_POS (3)
#define SYS_ANA_REG18_ENAUDBIAS_MASK (0x1)

#define SYS_ANA_REG18_ENADCBIAS_POS (4)
#define SYS_ANA_REG18_ENADCBIAS_MASK (0x1)

#define SYS_ANA_REG18_ENMICBIAS_POS (5)
#define SYS_ANA_REG18_ENMICBIAS_MASK (0x1)

#define SYS_ANA_REG18_ADCCKINVEN1V_POS (6)
#define SYS_ANA_REG18_ADCCKINVEN1V_MASK (0x1)

#define SYS_ANA_REG18_DACFB2ST0V9_POS (7)
#define SYS_ANA_REG18_DACFB2ST0V9_MASK (0x1)

#define SYS_ANA_REG18_NC1_POS (8)
#define SYS_ANA_REG18_NC1_MASK (0x1)

#define SYS_ANA_REG18_MICBIAS_TRM_POS (9)
#define SYS_ANA_REG18_MICBIAS_TRM_MASK (0x3)

#define SYS_ANA_REG18_MICBIAS_VOC_POS (11)
#define SYS_ANA_REG18_MICBIAS_VOC_MASK (0x1f)

#define SYS_ANA_REG18_VREFSEL1V_POS (16)
#define SYS_ANA_REG18_VREFSEL1V_MASK (0x1)

#define SYS_ANA_REG18_CAPSWSPI_POS (17)
#define SYS_ANA_REG18_CAPSWSPI_MASK (0x1f)

#define SYS_ANA_REG18_ADREF_SEL_POS (22)
#define SYS_ANA_REG18_ADREF_SEL_MASK (0x3)

#define SYS_ANA_REG18_NC0_POS (24)
#define SYS_ANA_REG18_NC0_MASK (0x3)

#define SYS_ANA_REG18_RESERVED_BIT_26_30_POS (26)
#define SYS_ANA_REG18_RESERVED_BIT_26_30_MASK (0x1f)

#define SYS_ANA_REG18_SPI_DACCKPSSEL_POS (31)
#define SYS_ANA_REG18_SPI_DACCKPSSEL_MASK (0x1)

#define SYS_ANA_REG19_ADDR (SOC_SYS_REG_BASE + (0x53 << 2))

#define SYS_ANA_REG19_ISEL_POS (0)
#define SYS_ANA_REG19_ISEL_MASK (0x3)

#define SYS_ANA_REG19_MICIRSEL1_POS (2)
#define SYS_ANA_REG19_MICIRSEL1_MASK (0x1)

#define SYS_ANA_REG19_MICDACIT_POS (3)
#define SYS_ANA_REG19_MICDACIT_MASK (0x3)

#define SYS_ANA_REG19_MICDACIH_POS (5)
#define SYS_ANA_REG19_MICDACIH_MASK (0xff)

#define SYS_ANA_REG19_MICSINGLEEN_POS (13)
#define SYS_ANA_REG19_MICSINGLEEN_MASK (0x1)

#define SYS_ANA_REG19_DCCOMPEN_POS (14)
#define SYS_ANA_REG19_DCCOMPEN_MASK (0x1)

#define SYS_ANA_REG19_MICGAIN_POS (15)
#define SYS_ANA_REG19_MICGAIN_MASK (0xf)

#define SYS_ANA_REG19_MICDACEN_POS (19)
#define SYS_ANA_REG19_MICDACEN_MASK (0x1)

#define SYS_ANA_REG19_STG2LSEN1V_POS (20)
#define SYS_ANA_REG19_STG2LSEN1V_MASK (0x1)

#define SYS_ANA_REG19_OPENLOOPCAL1V_POS (21)
#define SYS_ANA_REG19_OPENLOOPCAL1V_MASK (0x1)

#define SYS_ANA_REG19_CALLATCH_POS (22)
#define SYS_ANA_REG19_CALLATCH_MASK (0x1)

#define SYS_ANA_REG19_VCMSEL_POS (23)
#define SYS_ANA_REG19_VCMSEL_MASK (0x1)

#define SYS_ANA_REG19_DWAMODE_POS (24)
#define SYS_ANA_REG19_DWAMODE_MASK (0x1)

#define SYS_ANA_REG19_R2REN_POS (25)
#define SYS_ANA_REG19_R2REN_MASK (0x1)

#define SYS_ANA_REG19_NC_26_27_POS (26)
#define SYS_ANA_REG19_NC_26_27_MASK (0x3)

#define SYS_ANA_REG19_MICEN_POS (28)
#define SYS_ANA_REG19_MICEN_MASK (0x1)

#define SYS_ANA_REG19_RST_POS (29)
#define SYS_ANA_REG19_RST_MASK (0x1)

#define SYS_ANA_REG19_BPDWA1V_POS (30)
#define SYS_ANA_REG19_BPDWA1V_MASK (0x1)

#define SYS_ANA_REG19_HCEN1STG_POS (31)
#define SYS_ANA_REG19_HCEN1STG_MASK (0x1)

#define SYS_ANA_REG20_ADDR (SOC_SYS_REG_BASE + (0x54 << 2))

#define SYS_ANA_REG20_HPDAC_POS (0)
#define SYS_ANA_REG20_HPDAC_MASK (0x1)

#define SYS_ANA_REG20_CALCON_SEL_POS (1)
#define SYS_ANA_REG20_CALCON_SEL_MASK (0x1)

#define SYS_ANA_REG20_OSCDAC_POS (2)
#define SYS_ANA_REG20_OSCDAC_MASK (0x3)

#define SYS_ANA_REG20_OCENDAC_POS (4)
#define SYS_ANA_REG20_OCENDAC_MASK (0x1)

#define SYS_ANA_REG20_VCMSEL_POS (5)
#define SYS_ANA_REG20_VCMSEL_MASK (0x1)

#define SYS_ANA_REG20_ADJDACREF_POS (6)
#define SYS_ANA_REG20_ADJDACREF_MASK (0x1f)

#define SYS_ANA_REG20_DCOCHG_POS (11)
#define SYS_ANA_REG20_DCOCHG_MASK (0x3)

#define SYS_ANA_REG20_DIFFEN_POS (13)
#define SYS_ANA_REG20_DIFFEN_MASK (0x1)

#define SYS_ANA_REG20_ENDACCAL_POS (14)
#define SYS_ANA_REG20_ENDACCAL_MASK (0x1)

#define SYS_ANA_REG20_NC2_POS (15)
#define SYS_ANA_REG20_NC2_MASK (0x1)

#define SYS_ANA_REG20_LENDCOC_POS (16)
#define SYS_ANA_REG20_LENDCOC_MASK (0x1)

#define SYS_ANA_REG20_NC1_POS (17)
#define SYS_ANA_REG20_NC1_MASK (0x1)

#define SYS_ANA_REG20_LENVCMD_POS (18)
#define SYS_ANA_REG20_LENVCMD_MASK (0x1)

#define SYS_ANA_REG20_DACDRVEN_POS (19)
#define SYS_ANA_REG20_DACDRVEN_MASK (0x1)

#define SYS_ANA_REG20_NC0_POS (20)
#define SYS_ANA_REG20_NC0_MASK (0x1)

#define SYS_ANA_REG20_DACLEN_POS (21)
#define SYS_ANA_REG20_DACLEN_MASK (0x1)

#define SYS_ANA_REG20_DACG_POS (22)
#define SYS_ANA_REG20_DACG_MASK (0xf)

#define SYS_ANA_REG20_DACMUTE_POS (26)
#define SYS_ANA_REG20_DACMUTE_MASK (0x1)

#define SYS_ANA_REG20_DACDWAMODE_SEL_POS (27)
#define SYS_ANA_REG20_DACDWAMODE_SEL_MASK (0x1)

#define SYS_ANA_REG20_DACSEL_POS (28)
#define SYS_ANA_REG20_DACSEL_MASK (0xf)

#define SYS_ANA_REG21_ADDR (SOC_SYS_REG_BASE + (0x55 << 2))

#define SYS_ANA_REG21_LMDCIN_POS (0)
#define SYS_ANA_REG21_LMDCIN_MASK (0xff)

#define SYS_ANA_REG21_NC1_POS (8)
#define SYS_ANA_REG21_NC1_MASK (0xff)

#define SYS_ANA_REG21_SPIRST_OVC_POS (16)
#define SYS_ANA_REG21_SPIRST_OVC_MASK (0x1)

#define SYS_ANA_REG21_NC0_POS (17)
#define SYS_ANA_REG21_NC0_MASK (0x1)

#define SYS_ANA_REG21_ENIDACL_POS (18)
#define SYS_ANA_REG21_ENIDACL_MASK (0x1)

#define SYS_ANA_REG21_DAC3RDHC0V9_POS (19)
#define SYS_ANA_REG21_DAC3RDHC0V9_MASK (0x1)

#define SYS_ANA_REG21_HC2S_POS (20)
#define SYS_ANA_REG21_HC2S_MASK (0x1)

#define SYS_ANA_REG21_RFB_CTRL_POS (21)
#define SYS_ANA_REG21_RFB_CTRL_MASK (0x1)

#define SYS_ANA_REG21_VCMSEL_POS (22)
#define SYS_ANA_REG21_VCMSEL_MASK (0x1)

#define SYS_ANA_REG21_ENBS_POS (23)
#define SYS_ANA_REG21_ENBS_MASK (0x1)

#define SYS_ANA_REG21_CALCK_SEL0V9_POS (24)
#define SYS_ANA_REG21_CALCK_SEL0V9_MASK (0x1)

#define SYS_ANA_REG21_BPDWA0V9_POS (25)
#define SYS_ANA_REG21_BPDWA0V9_MASK (0x1)

#define SYS_ANA_REG21_LOOPRST0V9_POS (26)
#define SYS_ANA_REG21_LOOPRST0V9_MASK (0x1)

#define SYS_ANA_REG21_OCT0V9_POS (27)
#define SYS_ANA_REG21_OCT0V9_MASK (0x3)

#define SYS_ANA_REG21_SOUT0V9_POS (29)
#define SYS_ANA_REG21_SOUT0V9_MASK (0x1)

#define SYS_ANA_REG21_HC0V9_POS (30)
#define SYS_ANA_REG21_HC0V9_MASK (0x3)

#define SYS_ANA_REG22_ADDR (SOC_SYS_REG_BASE + (0x56 << 2))

#define SYS_ANA_REG22_ICTRL_DSPPLL_POS (0)
#define SYS_ANA_REG22_ICTRL_DSPPLL_MASK (0xf)

#define SYS_ANA_REG22_NC_4_18_POS (4)
#define SYS_ANA_REG22_NC_4_18_MASK (0x7fff)

#define SYS_ANA_REG22_MODE_POS (19)
#define SYS_ANA_REG22_MODE_MASK (0x1)

#define SYS_ANA_REG22_IAMSEL_POS (20)
#define SYS_ANA_REG22_IAMSEL_MASK (0x1)

#define SYS_ANA_REG22_HVREF_POS (21)
#define SYS_ANA_REG22_HVREF_MASK (0x3)

#define SYS_ANA_REG22_LVREF_POS (23)
#define SYS_ANA_REG22_LVREF_MASK (0x3)

#define SYS_ANA_REG22_NC_25_31_POS (25)
#define SYS_ANA_REG22_NC_25_31_MASK (0x7f)

#define SYS_ANA_REG23_ADDR (SOC_SYS_REG_BASE + (0x57 << 2))

#define SYS_ANA_REG23_CAMSEL_POS (0)
#define SYS_ANA_REG23_CAMSEL_MASK (0x1)

#define SYS_ANA_REG23_MSW_POS (1)
#define SYS_ANA_REG23_MSW_MASK (0x1ff)

#define SYS_ANA_REG23_TSTCKEN_DPLL_POS (10)
#define SYS_ANA_REG23_TSTCKEN_DPLL_MASK (0x1)

#define SYS_ANA_REG23_OSCCAL_TRIG_POS (11)
#define SYS_ANA_REG23_OSCCAL_TRIG_MASK (0x1)

#define SYS_ANA_REG23_CNTI_POS (12)
#define SYS_ANA_REG23_CNTI_MASK (0x1ff)

#define SYS_ANA_REG23_NC_21_21_POS (21)
#define SYS_ANA_REG23_NC_21_21_MASK (0x1)

#define SYS_ANA_REG23_SPI_RST_POS (22)
#define SYS_ANA_REG23_SPI_RST_MASK (0x1)

#define SYS_ANA_REG23_CLOSELOOP_EN_POS (23)
#define SYS_ANA_REG23_CLOSELOOP_EN_MASK (0x1)

#define SYS_ANA_REG23_CALTIME_POS (24)
#define SYS_ANA_REG23_CALTIME_MASK (0x1)

#define SYS_ANA_REG23_LPFRZ_POS (25)
#define SYS_ANA_REG23_LPFRZ_MASK (0x3)

#define SYS_ANA_REG23_ICP_POS (27)
#define SYS_ANA_REG23_ICP_MASK (0xf)

#define SYS_ANA_REG23_CP2CTRL_POS (31)
#define SYS_ANA_REG23_CP2CTRL_MASK (0x1)

#ifdef __cplusplus
}
#endif
