// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: demo1

#include "../ui.h"

void ui_UiPage2_screen_init(lv_obj_t *parent)
{
    ui_UiPage2 = lv_obj_create(parent);
    lv_obj_clear_flag(ui_UiPage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UiPage2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UiPage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_size(ui_UiPage2, LV_HOR_RES, LV_VER_RES);
    lv_obj_set_style_border_width(ui_UiPage2, 0, 0);
    lv_obj_set_style_pad_all(ui_UiPage2, 0, 0);
    lv_obj_set_style_radius(ui_UiPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui2Tittle = lv_label_create(ui_UiPage2);
    lv_obj_set_width(ui_Ui2Tittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui2Tittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui2Tittle, 20);
    lv_obj_set_y(ui_Ui2Tittle, 20);
    lv_label_set_text(ui_Ui2Tittle, "照明");
    lv_obj_set_style_text_color(ui_Ui2Tittle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui2Tittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui2Tittle, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui2Panel2 = lv_obj_create(ui_UiPage2);
    lv_obj_set_width(ui_Ui2Panel2, 400);
    lv_obj_set_height(ui_Ui2Panel2, 100);
    lv_obj_set_x(ui_Ui2Panel2, 40);
    lv_obj_set_y(ui_Ui2Panel2, 200);
    lv_obj_add_flag(ui_Ui2Panel2, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui2Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Ui2Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui2Panel2, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui2Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui2Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui2Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui2Panel2, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui2Panel2Label = lv_label_create(ui_Ui2Panel2);
    lv_obj_set_width(ui_Ui2Panel2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui2Panel2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui2Panel2Label, 0);
    lv_obj_set_y(ui_Ui2Panel2Label, -20);
    lv_obj_set_align(ui_Ui2Panel2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui2Panel2Label, "开关1-床头灯");
    lv_obj_set_style_text_color(ui_Ui2Panel2Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui2Panel2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui2Panel2Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui2Panel2Label, &ui_font_FontHei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui2Panel2Value = lv_label_create(ui_Ui2Panel2);
    lv_obj_set_width(ui_Ui2Panel2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui2Panel2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui2Panel2Value, 0);
    lv_obj_set_y(ui_Ui2Panel2Value, 10);
    lv_obj_set_align(ui_Ui2Panel2Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui2Panel2Value, "关");
    lv_obj_set_style_text_color(ui_Ui2Panel2Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui2Panel2Value, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui2Panel2Value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui2Panel2Value, &ui_font_FontHei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui2Panel2Img = lv_obj_create(ui_Ui2Panel2);
    lv_obj_set_width(ui_Ui2Panel2Img, 66);
    lv_obj_set_height(ui_Ui2Panel2Img, 68);
    lv_obj_set_align(ui_Ui2Panel2Img, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Ui2Panel2Img, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui2Panel2Img, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ui2Panel2Img, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui2Panel2Img, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Ui2Panel2Img, &ui_img_light_symbol_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui2Panel2Img, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Ui2Panel2Img, &ui_img_light_symbol_on_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Ui2Panel1 = lv_obj_create(ui_UiPage2);
    lv_obj_set_width(ui_Ui2Panel1, 180);
    lv_obj_set_height(ui_Ui2Panel1, 100);
    lv_obj_set_x(ui_Ui2Panel1, 40);
    lv_obj_set_y(ui_Ui2Panel1, 70);
    lv_obj_add_flag(ui_Ui2Panel1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui2Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Ui2Panel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui2Panel1, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui2Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui2Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui2Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui2Panel1, 110, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_Ui2Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_Ui2Panel1, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui2Panel1Tittle = lv_label_create(ui_Ui2Panel1);
    lv_obj_set_width(ui_Ui2Panel1Tittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui2Panel1Tittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ui2Panel1Tittle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui2Panel1Tittle, "全开");
    lv_obj_set_style_text_color(ui_Ui2Panel1Tittle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui2Panel1Tittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui2Panel1Tittle, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui2Panel1Tittle, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui2Panel4 = lv_obj_create(ui_UiPage2);
    lv_obj_set_width(ui_Ui2Panel4, 400);
    lv_obj_set_height(ui_Ui2Panel4, 100);
    lv_obj_set_x(ui_Ui2Panel4, 40);
    lv_obj_set_y(ui_Ui2Panel4, 330);
    lv_obj_add_flag(ui_Ui2Panel4, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui2Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Ui2Panel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui2Panel4, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui2Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui2Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui2Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui2Panel4, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui2Panel4Label1 = lv_label_create(ui_Ui2Panel4);
    lv_obj_set_width(ui_Ui2Panel4Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui2Panel4Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui2Panel4Label1, 0);
    lv_obj_set_y(ui_Ui2Panel4Label1, -20);
    lv_obj_set_align(ui_Ui2Panel4Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui2Panel4Label1, "开关2-主卧灯");
    lv_obj_set_style_text_color(ui_Ui2Panel4Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui2Panel4Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui2Panel4Label1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui2Panel4Label1, &ui_font_FontHei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui2Panel4Value = lv_label_create(ui_Ui2Panel4);
    lv_obj_set_width(ui_Ui2Panel4Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui2Panel4Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui2Panel4Value, 0);
    lv_obj_set_y(ui_Ui2Panel4Value, 10);
    lv_obj_set_align(ui_Ui2Panel4Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui2Panel4Value, "关");
    lv_obj_set_style_text_color(ui_Ui2Panel4Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui2Panel4Value, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui2Panel4Value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui2Panel4Value, &ui_font_FontHei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui2Panel4Img = lv_obj_create(ui_Ui2Panel4);
    lv_obj_set_width(ui_Ui2Panel4Img, 66);
    lv_obj_set_height(ui_Ui2Panel4Img, 68);
    lv_obj_set_align(ui_Ui2Panel4Img, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Ui2Panel4Img, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui2Panel4Img, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ui2Panel4Img, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui2Panel4Img, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Ui2Panel4Img, &ui_img_light_symbol_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui2Panel4Img, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Ui2Panel4Img, &ui_img_light_symbol_on_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Ui2Panel3 = lv_obj_create(ui_UiPage2);
    lv_obj_set_width(ui_Ui2Panel3, 180);
    lv_obj_set_height(ui_Ui2Panel3, 100);
    lv_obj_set_x(ui_Ui2Panel3, -40);
    lv_obj_set_y(ui_Ui2Panel3, 70);
    lv_obj_set_align(ui_Ui2Panel3, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Ui2Panel3, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui2Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Ui2Panel3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui2Panel3, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui2Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui2Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui2Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui2Panel3, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui2Panel1Tittle1 = lv_label_create(ui_Ui2Panel3);
    lv_obj_set_width(ui_Ui2Panel1Tittle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui2Panel1Tittle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ui2Panel1Tittle1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui2Panel1Tittle1, "全关");
    lv_obj_set_style_text_color(ui_Ui2Panel1Tittle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui2Panel1Tittle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui2Panel1Tittle1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui2Panel1Tittle1, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Ui2Panel2, ui_event_Ui2Panel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Ui2Panel1, ui_event_Ui2Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Ui2Panel4, ui_event_Ui2Panel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Ui2Panel3, ui_event_Ui2Panel3, LV_EVENT_ALL, NULL);

}
