// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: demo1

#include "../ui.h"

void ui_UiPage3_screen_init(lv_obj_t *parent)
{
    ui_UiPage3 = lv_obj_create(parent);
    lv_obj_clear_flag(ui_UiPage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UiPage3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UiPage3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_size(ui_UiPage3, LV_HOR_RES, LV_VER_RES);
    lv_obj_set_style_border_width(ui_UiPage3, 0, 0);
    lv_obj_set_style_pad_all(ui_UiPage3, 0, 0);
    lv_obj_set_style_radius(ui_UiPage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui3Tittle = lv_label_create(ui_UiPage3);
    lv_obj_set_width(ui_Ui3Tittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui3Tittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui3Tittle, 20);
    lv_obj_set_y(ui_Ui3Tittle, 20);
    lv_label_set_text(ui_Ui3Tittle, "窗帘");
    lv_obj_set_style_text_color(ui_Ui3Tittle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui3Tittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui3Tittle, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui3Panel1 = lv_obj_create(ui_UiPage3);
    lv_obj_set_width(ui_Ui3Panel1, 400);
    lv_obj_set_height(ui_Ui3Panel1, 120);
    lv_obj_set_x(ui_Ui3Panel1, 40);
    lv_obj_set_y(ui_Ui3Panel1, 100);
    lv_obj_add_flag(ui_Ui3Panel1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui3Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Ui3Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui3Panel1, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui3Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui3Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui3Panel1Label = lv_label_create(ui_Ui3Panel1);
    lv_obj_set_width(ui_Ui3Panel1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui3Panel1Label, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Ui3Panel1Label, "对开帘");
    lv_obj_set_style_text_color(ui_Ui3Panel1Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui3Panel1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui3Panel1Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui3Panel1Label, &ui_font_FontHei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UI3Panel1Stop = lv_img_create(ui_Ui3Panel1);
    lv_img_set_src(ui_UI3Panel1Stop, &ui_img_curtain_stop_png);
    lv_obj_set_width(ui_UI3Panel1Stop, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_UI3Panel1Stop, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_UI3Panel1Stop, 0);
    lv_obj_set_y(ui_UI3Panel1Stop, 2);
    lv_obj_set_align(ui_UI3Panel1Stop, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_UI3Panel1Stop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_UI3Panel1Stop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_UI3Panel1Stop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_UI3Panel1Stop, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_UI3Panel1On = lv_img_create(ui_Ui3Panel1);
    lv_img_set_src(ui_UI3Panel1On, &ui_img_curtain_off_png);
    lv_obj_set_width(ui_UI3Panel1On, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UI3Panel1On, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UI3Panel1On, 70);
    lv_obj_set_y(ui_UI3Panel1On, 0);
    lv_obj_set_align(ui_UI3Panel1On, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_UI3Panel1On, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_UI3Panel1On, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_UI3Panel1On, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_UI3Panel1On, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_UI3Panel1Off = lv_img_create(ui_Ui3Panel1);
    lv_img_set_src(ui_UI3Panel1Off, &ui_img_curtain_on_png);
    lv_obj_set_width(ui_UI3Panel1Off, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UI3Panel1Off, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UI3Panel1Off, -70);
    lv_obj_set_y(ui_UI3Panel1Off, 0);
    lv_obj_set_align(ui_UI3Panel1Off, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_UI3Panel1Off, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_UI3Panel1Off, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_UI3Panel1Off, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_UI3Panel1Off, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui3Panel2 = lv_obj_create(ui_UiPage3);
    lv_obj_set_width(ui_Ui3Panel2, 400);
    lv_obj_set_height(ui_Ui3Panel2, 120);
    lv_obj_set_x(ui_Ui3Panel2, 40);
    lv_obj_set_y(ui_Ui3Panel2, 280);
    lv_obj_add_flag(ui_Ui3Panel2, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui3Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Ui3Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui3Panel2, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui3Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui3Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui3Panel2Label = lv_label_create(ui_Ui3Panel2);
    lv_obj_set_width(ui_Ui3Panel2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui3Panel2Label, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Ui3Panel2Label, "卷帘");
    lv_obj_set_style_text_color(ui_Ui3Panel2Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui3Panel2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui3Panel2Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui3Panel2Label, &ui_font_FontHei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UI3Panel2Stop = lv_img_create(ui_Ui3Panel2);
    lv_img_set_src(ui_UI3Panel2Stop, &ui_img_curtain_stop_png);
    lv_obj_set_width(ui_UI3Panel2Stop, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_UI3Panel2Stop, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_UI3Panel2Stop, 0);
    lv_obj_set_y(ui_UI3Panel2Stop, 2);
    lv_obj_set_align(ui_UI3Panel2Stop, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_UI3Panel2Stop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_UI3Panel2Stop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_UI3Panel2Stop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_UI3Panel2Stop, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_UI3Panel2On = lv_img_create(ui_Ui3Panel2);
    lv_img_set_src(ui_UI3Panel2On, &ui_img_curtain_off_png);
    lv_obj_set_width(ui_UI3Panel2On, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UI3Panel2On, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UI3Panel2On, 70);
    lv_obj_set_y(ui_UI3Panel2On, 0);
    lv_obj_set_align(ui_UI3Panel2On, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_UI3Panel2On, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_UI3Panel2On, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_UI3Panel2On, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_UI3Panel2On, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_UI3Panel2Off = lv_img_create(ui_Ui3Panel2);
    lv_img_set_src(ui_UI3Panel2Off, &ui_img_curtain_on_png);
    lv_obj_set_width(ui_UI3Panel2Off, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UI3Panel2Off, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UI3Panel2Off, -70);
    lv_obj_set_y(ui_UI3Panel2Off, 0);
    lv_obj_set_align(ui_UI3Panel2Off, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_UI3Panel2Off, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_UI3Panel2Off, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_UI3Panel2Off, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_UI3Panel2Off, 50, LV_PART_MAIN | LV_STATE_PRESSED);

}
