// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: demo1

#include "../ui.h"

void ui_UiPage1_screen_init(lv_obj_t *parent)
{
    ui_UiPage1 = lv_obj_create(parent);
    lv_obj_clear_flag(ui_UiPage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_size(ui_UiPage1, LV_HOR_RES, LV_VER_RES);
    lv_obj_set_style_border_width(ui_UiPage1, 0, 0);
    lv_obj_set_style_pad_all(ui_UiPage1, 0, 0);

    ui_Ui1Bg = lv_img_create(ui_UiPage1);
    lv_img_set_src(ui_Ui1Bg, &ui_img_bg_img_png);
    lv_obj_set_width(ui_Ui1Bg, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Ui1Bg, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Ui1Bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Ui1Bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ui1Bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ui1WifiSymbol = lv_img_create(ui_UiPage1);
    lv_img_set_src(ui_Ui1WifiSymbol, &ui_img_wifi_symbol_png);
    lv_obj_set_width(ui_Ui1WifiSymbol, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Ui1WifiSymbol, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_Ui1WifiSymbol, -30);
    lv_obj_set_y(ui_Ui1WifiSymbol, 10);
    lv_obj_set_align(ui_Ui1WifiSymbol, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Ui1WifiSymbol, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ui1WifiSymbol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ui1TimeLabel = lv_label_create(ui_UiPage1);
    lv_obj_set_width(ui_Ui1TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui1TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui1TimeLabel, 87);
    lv_obj_set_y(ui_Ui1TimeLabel, -102);
    lv_obj_set_align(ui_Ui1TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui1TimeLabel, "10:21");
    lv_obj_set_style_text_color(ui_Ui1TimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui1TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui1TimeLabel, &ui_font_OppoSanMid96, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui1EDateLabel = lv_label_create(ui_UiPage1);
    lv_obj_set_width(ui_Ui1EDateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui1EDateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui1EDateLabel, -74);
    lv_obj_set_y(ui_Ui1EDateLabel, -39);
    lv_obj_set_align(ui_Ui1EDateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui1EDateLabel, "5月31日");
    lv_obj_set_style_text_color(ui_Ui1EDateLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui1EDateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui1EDateLabel, &ui_font_OppoCN24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui1WeekLabel = lv_label_create(ui_UiPage1);
    lv_obj_set_width(ui_Ui1WeekLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui1WeekLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui1WeekLabel, 9);
    lv_obj_set_y(ui_Ui1WeekLabel, -39);
    lv_obj_set_align(ui_Ui1WeekLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui1WeekLabel, "星期三");
    lv_obj_set_style_text_color(ui_Ui1WeekLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui1WeekLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui1WeekLabel, &ui_font_OppoCN24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui1CDateLabel = lv_label_create(ui_UiPage1);
    lv_obj_set_width(ui_Ui1CDateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui1CDateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui1CDateLabel, 95);
    lv_obj_set_y(ui_Ui1CDateLabel, -39);
    lv_obj_set_align(ui_Ui1CDateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui1CDateLabel, "正月初八");
    lv_obj_set_style_text_color(ui_Ui1CDateLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui1CDateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui1CDateLabel, &ui_font_OppoCN24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui1WeatherImg = lv_img_create(ui_UiPage1);
    lv_img_set_src(ui_Ui1WeatherImg, &ui_img_sun_png);
    lv_obj_set_width(ui_Ui1WeatherImg, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Ui1WeatherImg, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Ui1WeatherImg, 165);
    lv_obj_set_y(ui_Ui1WeatherImg, -39);
    lv_obj_set_align(ui_Ui1WeatherImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Ui1WeatherImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ui1WeatherImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ui1WeatherLabel = lv_label_create(ui_UiPage1);
    lv_obj_set_width(ui_Ui1WeatherLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui1WeatherLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui1WeatherLabel, 205);
    lv_obj_set_y(ui_Ui1WeatherLabel, -39);
    lv_obj_set_align(ui_Ui1WeatherLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui1WeatherLabel, "27℃");
    lv_obj_set_style_text_color(ui_Ui1WeatherLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui1WeatherLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui1WeatherLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui1WeatherLabel, &ui_font_OppoCN24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui1Panel1 = lv_obj_create(ui_UiPage1);
    lv_obj_set_width(ui_Ui1Panel1, 200);
    lv_obj_set_height(ui_Ui1Panel1, 100);
    lv_obj_set_x(ui_Ui1Panel1, -25);
    lv_obj_set_y(ui_Ui1Panel1, 120);
    lv_obj_set_align(ui_Ui1Panel1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Ui1Panel1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui1Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Ui1Panel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui1Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui1Panel1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui1Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui1Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui1Panel1, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui1Panel1Label = lv_label_create(ui_Ui1Panel1);
    lv_obj_set_width(ui_Ui1Panel1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui1Panel1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui1Panel1Label, -20);
    lv_obj_set_y(ui_Ui1Panel1Label, 10);
    lv_obj_set_align(ui_Ui1Panel1Label, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Ui1Panel1Label, "主卧灯");
    lv_obj_set_style_text_color(ui_Ui1Panel1Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui1Panel1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui1Panel1Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui1Panel1Label, &ui_font_OppoCN24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui1Panel1Value = lv_label_create(ui_Ui1Panel1);
    lv_obj_set_width(ui_Ui1Panel1Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui1Panel1Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui1Panel1Value, -40);
    lv_obj_set_y(ui_Ui1Panel1Value, 20);
    lv_obj_set_align(ui_Ui1Panel1Value, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Ui1Panel1Value, "关");
    lv_obj_set_style_text_color(ui_Ui1Panel1Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui1Panel1Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui1Panel1Value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui1Panel1Value, &ui_font_OppoCN24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui1Panel1Img = lv_obj_create(ui_Ui1Panel1);
    lv_obj_set_width(ui_Ui1Panel1Img, 66);
    lv_obj_set_height(ui_Ui1Panel1Img, 68);
    lv_obj_set_align(ui_Ui1Panel1Img, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Ui1Panel1Img, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui1Panel1Img, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ui1Panel1Img, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui1Panel1Img, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Ui1Panel1Img, &ui_img_light_symbol_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui1Panel1Img, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Ui1Panel1Img, &ui_img_light_symbol_on_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Ui1Panel2 = lv_obj_create(ui_UiPage1);
    lv_obj_set_width(ui_Ui1Panel2, 200);
    lv_obj_set_height(ui_Ui1Panel2, 100);
    lv_obj_set_x(ui_Ui1Panel2, 25);
    lv_obj_set_y(ui_Ui1Panel2, 120);
    lv_obj_set_align(ui_Ui1Panel2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Ui1Panel2, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui1Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Ui1Panel2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui1Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui1Panel2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui1Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui1Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui1Panel2, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui1Panel2Label = lv_label_create(ui_Ui1Panel2);
    lv_obj_set_width(ui_Ui1Panel2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui1Panel2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui1Panel2Label, -20);
    lv_obj_set_y(ui_Ui1Panel2Label, 10);
    lv_obj_set_align(ui_Ui1Panel2Label, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Ui1Panel2Label, "床头灯");
    lv_obj_set_style_text_color(ui_Ui1Panel2Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui1Panel2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui1Panel2Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui1Panel2Label, &ui_font_OppoCN24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui1Panel2Value = lv_label_create(ui_Ui1Panel2);
    lv_obj_set_width(ui_Ui1Panel2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui1Panel2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui1Panel2Value, -40);
    lv_obj_set_y(ui_Ui1Panel2Value, 20);
    lv_obj_set_align(ui_Ui1Panel2Value, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Ui1Panel2Value, "关");
    lv_obj_set_style_text_color(ui_Ui1Panel2Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui1Panel2Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui1Panel2Value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui1Panel2Value, &ui_font_OppoCN24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui1Panel2Img = lv_obj_create(ui_Ui1Panel2);
    lv_obj_set_width(ui_Ui1Panel2Img, 66);
    lv_obj_set_height(ui_Ui1Panel2Img, 68);
    lv_obj_set_align(ui_Ui1Panel2Img, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Ui1Panel2Img, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui1Panel2Img, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ui1Panel2Img, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui1Panel2Img, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Ui1Panel2Img, &ui_img_light_symbol_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui1Panel2Img, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Ui1Panel2Img, &ui_img_light_symbol_on_png, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_Ui1Panel1, ui_event_Ui1Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Ui1Panel2, ui_event_Ui1Panel2, LV_EVENT_ALL, NULL);
}
