// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: AiotArc

#include "../ui.h"

void ui_UiPage6_screen_init(void)
{
    ui_UiPage6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_UiPage6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UiPage6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UiPage6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_size(ui_UiPage6, LV_HOR_RES, LV_VER_RES);
    lv_obj_set_style_border_width(ui_UiPage6, 0, 0);
    lv_obj_set_style_pad_all(ui_UiPage6, 0, 0);
    lv_obj_set_style_radius(ui_UiPage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui6Panel1 = lv_obj_create(ui_UiPage6);
    lv_obj_set_width(ui_Ui6Panel1, 200);
    lv_obj_set_height(ui_Ui6Panel1, 120);
    lv_obj_set_x(ui_Ui6Panel1, 20);
    lv_obj_set_y(ui_Ui6Panel1, 30);
    lv_obj_clear_flag(ui_Ui6Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ui6Panel1, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui6Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui6Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui6Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui6Panel1, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui6Symbol1 = lv_img_create(ui_Ui6Panel1);
    lv_img_set_src(ui_Ui6Symbol1, &ui_img_first_page_png);
    lv_obj_set_width(ui_Ui6Symbol1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui6Symbol1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ui6Symbol1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Ui6Symbol1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ui6Symbol1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ui6Label1 = lv_label_create(ui_Ui6Panel1);
    lv_obj_set_width(ui_Ui6Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui6Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui6Label1, 70);
    lv_obj_set_y(ui_Ui6Label1, 0);
    lv_obj_set_align(ui_Ui6Label1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Ui6Label1, "首页");
    lv_obj_set_style_text_color(ui_Ui6Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui6Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui6Label1, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui6Panel2 = lv_obj_create(ui_UiPage6);
    lv_obj_set_width(ui_Ui6Panel2, 200);
    lv_obj_set_height(ui_Ui6Panel2, 120);
    lv_obj_set_x(ui_Ui6Panel2, 260);
    lv_obj_set_y(ui_Ui6Panel2, 30);
    lv_obj_clear_flag(ui_Ui6Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ui6Panel2, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui6Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui6Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui6Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui6Panel2, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui6Symbol2 = lv_img_create(ui_Ui6Panel2);
    lv_img_set_src(ui_Ui6Symbol2, &ui_img_light_page_png);
    lv_obj_set_width(ui_Ui6Symbol2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui6Symbol2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ui6Symbol2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Ui6Symbol2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ui6Symbol2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ui6Label2 = lv_label_create(ui_Ui6Panel2);
    lv_obj_set_width(ui_Ui6Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui6Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui6Label2, 70);
    lv_obj_set_y(ui_Ui6Label2, 0);
    lv_obj_set_align(ui_Ui6Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Ui6Label2, "照明");
    lv_obj_set_style_text_color(ui_Ui6Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui6Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui6Label2, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui6Panel3 = lv_obj_create(ui_UiPage6);
    lv_obj_set_width(ui_Ui6Panel3, 200);
    lv_obj_set_height(ui_Ui6Panel3, 120);
    lv_obj_set_x(ui_Ui6Panel3, 20);
    lv_obj_set_y(ui_Ui6Panel3, 180);
    lv_obj_clear_flag(ui_Ui6Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ui6Panel3, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui6Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui6Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui6Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui6Panel3, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui6Symbol3 = lv_img_create(ui_Ui6Panel3);
    lv_img_set_src(ui_Ui6Symbol3, &ui_img_air_page_png);
    lv_obj_set_width(ui_Ui6Symbol3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui6Symbol3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ui6Symbol3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Ui6Symbol3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ui6Symbol3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ui6Label3 = lv_label_create(ui_Ui6Panel3);
    lv_obj_set_width(ui_Ui6Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui6Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui6Label3, 70);
    lv_obj_set_y(ui_Ui6Label3, 0);
    lv_obj_set_align(ui_Ui6Label3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Ui6Label3, "空调");
    lv_obj_set_style_text_color(ui_Ui6Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui6Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui6Label3, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui6Panel4 = lv_obj_create(ui_UiPage6);
    lv_obj_set_width(ui_Ui6Panel4, 200);
    lv_obj_set_height(ui_Ui6Panel4, 120);
    lv_obj_set_x(ui_Ui6Panel4, 260);
    lv_obj_set_y(ui_Ui6Panel4, 180);
    lv_obj_clear_flag(ui_Ui6Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ui6Panel4, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui6Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui6Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui6Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui6Panel4, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui6Symbol4 = lv_img_create(ui_Ui6Panel4);
    lv_img_set_src(ui_Ui6Symbol4, &ui_img_curtain_page_png);
    lv_obj_set_width(ui_Ui6Symbol4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui6Symbol4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ui6Symbol4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Ui6Symbol4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ui6Symbol4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ui6Label4 = lv_label_create(ui_Ui6Panel4);
    lv_obj_set_width(ui_Ui6Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui6Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui6Label4, 70);
    lv_obj_set_y(ui_Ui6Label4, 0);
    lv_obj_set_align(ui_Ui6Label4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Ui6Label4, "窗帘");
    lv_obj_set_style_text_color(ui_Ui6Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui6Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui6Label4, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui6Panel5 = lv_obj_create(ui_UiPage6);
    lv_obj_set_width(ui_Ui6Panel5, 200);
    lv_obj_set_height(ui_Ui6Panel5, 120);
    lv_obj_set_x(ui_Ui6Panel5, 20);
    lv_obj_set_y(ui_Ui6Panel5, 330);
    lv_obj_clear_flag(ui_Ui6Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ui6Panel5, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui6Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui6Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui6Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui6Panel5, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui6Symbol5 = lv_img_create(ui_Ui6Panel5);
    lv_img_set_src(ui_Ui6Symbol5, &ui_img_mode_page_png);
    lv_obj_set_width(ui_Ui6Symbol5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui6Symbol5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ui6Symbol5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Ui6Symbol5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ui6Symbol5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ui6Label5 = lv_label_create(ui_Ui6Panel5);
    lv_obj_set_width(ui_Ui6Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui6Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui6Label5, 70);
    lv_obj_set_y(ui_Ui6Label5, 0);
    lv_obj_set_align(ui_Ui6Label5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Ui6Label5, "模式");
    lv_obj_set_style_text_color(ui_Ui6Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui6Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui6Label5, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui6Panel6 = lv_obj_create(ui_UiPage6);
    lv_obj_set_width(ui_Ui6Panel6, 200);
    lv_obj_set_height(ui_Ui6Panel6, 120);
    lv_obj_set_x(ui_Ui6Panel6, 260);
    lv_obj_set_y(ui_Ui6Panel6, 330);
    lv_obj_clear_flag(ui_Ui6Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ui6Panel6, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui6Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui6Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui6Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui6Panel6, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui6Symbol6 = lv_img_create(ui_Ui6Panel6);
    lv_img_set_src(ui_Ui6Symbol6, &ui_img_set_page_png);
    lv_obj_set_width(ui_Ui6Symbol6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui6Symbol6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ui6Symbol6, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Ui6Symbol6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ui6Symbol6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ui6Label6 = lv_label_create(ui_Ui6Panel6);
    lv_obj_set_width(ui_Ui6Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui6Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui6Label6, 70);
    lv_obj_set_y(ui_Ui6Label6, 0);
    lv_obj_set_align(ui_Ui6Label6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Ui6Label6, "设置");
    lv_obj_set_style_text_color(ui_Ui6Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui6Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui6Label6, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_UiPage6, ui_event_UiPage6_screen, LV_EVENT_ALL, (void *)1);
}
