// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: demo1

#include "../ui.h"

void ui_UiPage4_screen_init(lv_obj_t *parent)
{
    ui_UiPage4 = lv_obj_create(parent);
    lv_obj_clear_flag(ui_UiPage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UiPage4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UiPage4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_size(ui_UiPage4, LV_HOR_RES, LV_VER_RES);
    lv_obj_set_style_border_width(ui_UiPage4, 0, 0);
    lv_obj_set_style_pad_all(ui_UiPage4, 0, 0);
    lv_obj_set_style_radius(ui_UiPage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui4Tittle = lv_label_create(ui_UiPage4);
    lv_obj_set_width(ui_Ui4Tittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui4Tittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ui4Tittle, 20);
    lv_obj_set_y(ui_Ui4Tittle, 20);
    lv_label_set_text(ui_Ui4Tittle, "模式");
    lv_obj_set_style_text_color(ui_Ui4Tittle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui4Tittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui4Tittle, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui4Panel1 = lv_obj_create(ui_UiPage4);
    lv_obj_set_width(ui_Ui4Panel1, 400);
    lv_obj_set_height(ui_Ui4Panel1, 100);
    lv_obj_set_x(ui_Ui4Panel1, 0);
    lv_obj_set_y(ui_Ui4Panel1, 100);
    lv_obj_set_align(ui_Ui4Panel1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Ui4Panel1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui4Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Ui4Panel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui4Panel1, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui4Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui4Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui4Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui4Panel1, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui4Panel1Tittle = lv_label_create(ui_Ui4Panel1);
    lv_obj_set_width(ui_Ui4Panel1Tittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui4Panel1Tittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ui4Panel1Tittle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui4Panel1Tittle, "睡眠模式");
    lv_obj_set_style_text_color(ui_Ui4Panel1Tittle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui4Panel1Tittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui4Panel1Tittle, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui4Panel1Tittle, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ui4Panel2 = lv_obj_create(ui_UiPage4);
    lv_obj_set_width(ui_Ui4Panel2, 400);
    lv_obj_set_height(ui_Ui4Panel2, 100);
    lv_obj_set_x(ui_Ui4Panel2, 0);
    lv_obj_set_y(ui_Ui4Panel2, 250);
    lv_obj_set_align(ui_Ui4Panel2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Ui4Panel2, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ui4Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Ui4Panel2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui4Panel2, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ui4Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Ui4Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ui4Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Ui4Panel2, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Ui4Panel2Tittle = lv_label_create(ui_Ui4Panel2);
    lv_obj_set_width(ui_Ui4Panel2Tittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ui4Panel2Tittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ui4Panel2Tittle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ui4Panel2Tittle, "起床模式");
    lv_obj_set_style_text_color(ui_Ui4Panel2Tittle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ui4Panel2Tittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Ui4Panel2Tittle, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ui4Panel2Tittle, &ui_font_FontHei32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Ui4Panel1, ui_event_Ui4Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Ui4Panel2, ui_event_Ui4Panel2, LV_EVENT_ALL, NULL);

}
