// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: demo1

#include "../ui.h"

void ui_UiPage1_screen_init(lv_obj_t *parent)
{
    ui_Screen1 = lv_obj_create(parent);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_size(ui_Screen1, LV_HOR_RES, LV_VER_RES);
    lv_obj_set_style_border_width(ui_Screen1, 0, 0);
    lv_obj_set_style_pad_all(ui_Screen1, 0, 0);
    lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sun = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_sun, &ui_img_sun_png);
    lv_obj_set_width(ui_sun, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sun, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sun, 306);
    lv_obj_set_y(ui_sun, 18);
    lv_obj_add_flag(ui_sun, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sun, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cloudBig = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_cloudBig, &ui_img_cloud_b_png);
    lv_obj_set_width(ui_cloudBig, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cloudBig, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cloudBig, 250);
    lv_obj_set_y(ui_cloudBig, 90);
    lv_obj_add_flag(ui_cloudBig, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cloudBig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cloudSmall2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_cloudSmall2, &ui_img_cloud_s_png);
    lv_obj_set_width(ui_cloudSmall2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cloudSmall2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cloudSmall2, 396);
    lv_obj_set_y(ui_cloudSmall2, 80);
    lv_obj_add_flag(ui_cloudSmall2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cloudSmall2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cloudSmall1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_cloudSmall1, &ui_img_cloud_s_png);
    lv_obj_set_width(ui_cloudSmall1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cloudSmall1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cloudSmall1, 246);
    lv_obj_set_y(ui_cloudSmall1, 29);
    lv_obj_add_flag(ui_cloudSmall1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cloudSmall1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, 154);
    lv_obj_set_y(ui_temp, 5);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "30°");
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp, &ui_font_FontHei96, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather, 190);
    lv_obj_set_y(ui_weather, 28);
    lv_obj_set_align(ui_weather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather, "多云");
    lv_obj_set_style_text_color(ui_weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather, &ui_font_FontHei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeInfo = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timeInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeInfo, 0);
    lv_obj_set_y(ui_timeInfo, 150);
    lv_obj_set_align(ui_timeInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeInfo, "11:20");
    lv_obj_set_style_text_color(ui_timeInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeInfo, &ui_font_FontHei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dataInfo = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_dataInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dataInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dataInfo, 0);
    lv_obj_set_y(ui_dataInfo, 185);
    lv_obj_set_align(ui_dataInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dataInfo, "6月14日星期三");
    lv_obj_set_style_text_color(ui_dataInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dataInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dataInfo, &ui_font_FontHei24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

