// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: demo1

#ifndef _DEMO1_UI_H
#define _DEMO1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "page_load_ctrol.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_UiPage1
void move_x_add_Animation(lv_obj_t * TargetObject, int delay);
void mov_x_sub_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_UiPage1_screen_init(lv_obj_t *parent);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_sun;
extern lv_obj_t * ui_cloudBig;
extern lv_obj_t * ui_cloudSmall2;
extern lv_obj_t * ui_cloudSmall1;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_timeInfo;
extern lv_obj_t * ui_dataInfo;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_sun_png);    // assets\sun.png
LV_IMG_DECLARE(ui_img_cloud_b_png);    // assets\cloud_b.png
LV_IMG_DECLARE(ui_img_cloud_s_png);    // assets\cloud_s.png

// SCREEN: ui_UiPage2
void ui_UiPage2_screen_init(lv_obj_t *parent);
extern lv_obj_t * ui_UiPage2;
extern lv_obj_t * ui_Ui2Tittle;
void ui_event_Ui2Panel2(lv_event_t * e);
extern lv_obj_t * ui_Ui2Panel2;
extern lv_obj_t * ui_Ui2Panel2Label;
extern lv_obj_t * ui_Ui2Panel2Value;
extern lv_obj_t * ui_Ui2Panel2Img;
void ui_event_Ui2Panel1(lv_event_t * e);
extern lv_obj_t * ui_Ui2Panel1;
extern lv_obj_t * ui_Ui2Panel1Tittle;
void ui_event_Ui2Panel4(lv_event_t * e);
extern lv_obj_t * ui_Ui2Panel4;
extern lv_obj_t * ui_Ui2Panel4Label1;
extern lv_obj_t * ui_Ui2Panel4Value;
extern lv_obj_t * ui_Ui2Panel4Img;
void ui_event_Ui2Panel3(lv_event_t * e);
extern lv_obj_t * ui_Ui2Panel3;
extern lv_obj_t * ui_Ui2Panel1Tittle1;
// SCREEN: ui_UiPage3
void ui_UiPage3_screen_init(lv_obj_t *parent);
extern lv_obj_t * ui_UiPage3;
extern lv_obj_t * ui_Ui3Tittle;
extern lv_obj_t * ui_Ui3Panel1;
extern lv_obj_t * ui_Ui3Panel1Label;
extern lv_obj_t * ui_UI3Panel1Stop;
extern lv_obj_t * ui_UI3Panel1On;
extern lv_obj_t * ui_UI3Panel1Off;
extern lv_obj_t * ui_Ui3Panel2;
extern lv_obj_t * ui_Ui3Panel2Label;
extern lv_obj_t * ui_UI3Panel2Stop;
extern lv_obj_t * ui_UI3Panel2On;
extern lv_obj_t * ui_UI3Panel2Off;
// SCREEN: ui_UiPage4
void ui_UiPage4_screen_init(lv_obj_t *parent);
extern lv_obj_t * ui_UiPage4;
extern lv_obj_t * ui_Ui4Tittle;
void ui_event_Ui4Panel1(lv_event_t * e);
extern lv_obj_t * ui_Ui4Panel1;
extern lv_obj_t * ui_Ui4Panel1Tittle;
void ui_event_Ui4Panel2(lv_event_t * e);
extern lv_obj_t * ui_Ui4Panel2;
extern lv_obj_t * ui_Ui4Panel2Tittle;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_bg_img_png);    // assets\bg_img.png
LV_IMG_DECLARE(ui_img_wifi_symbol_png);    // assets\wifi_symbol.png
LV_IMG_DECLARE(ui_img_light_symbol_off_png);    // assets\light_symbol_off.png
LV_IMG_DECLARE(ui_img_light_symbol_on_png);    // assets\light_symbol_on.png
LV_IMG_DECLARE(ui_img_curtain_stop_png);    // assets\curtain_stop.png
LV_IMG_DECLARE(ui_img_curtain_off_png);    // assets\curtain_off.png
LV_IMG_DECLARE(ui_img_curtain_on_png);    // assets\curtain_on.png
LV_IMG_DECLARE(ui_img_anime_lin2_png);    // assets\anime_lin2.png
LV_IMG_DECLARE(ui_img_anime_line1_png);    // assets\anime_line1.png
LV_IMG_DECLARE(ui_img_arrow1_png);    // assets\arrow1.png
LV_IMG_DECLARE(ui_img_cloud1_png);    // assets\cloud1.png
LV_IMG_DECLARE(ui_img_common_switch1_png);    // assets\common_switch1.png

LV_FONT_DECLARE(ui_font_FontHei24);
LV_FONT_DECLARE(ui_font_FontHei96);
LV_FONT_DECLARE(ui_font_FontHei32);

// SCREEN: ui_UiArcPage
void ui_UiArcPage_screen_init(lv_obj_t *parent);
extern lv_obj_t * ui_UiArcPage;
extern lv_obj_t * ui_UAPColdImg;
extern lv_obj_t * ui_WAPSwitchImg;
extern lv_obj_t * ui_UAPFanImg;
extern lv_obj_t * ui_UAPtittle;
extern lv_obj_t * ui_circleBg1;
extern lv_obj_t * ui_circleBg2;
extern lv_obj_t * ui_jianbutton;
extern lv_obj_t * ui_jiabutton;
extern lv_obj_t * ui_jian;
extern lv_obj_t * ui_jia1;
extern lv_obj_t * ui_jia2;
extern lv_obj_t * ui_tempDesc;
extern lv_obj_t * ui_tempValue;
extern lv_obj_t * ui_tempDan;
// SCREEN: ui_UiPage5
void ui_UiPage5_screen_init(lv_obj_t *parent);
extern lv_obj_t * ui_UiPage5;
extern lv_obj_t * ui_Ui5Tittle;
extern lv_obj_t * ui_Ui5Panel1;
extern lv_obj_t * ui_Ui5Symbol1;
extern lv_obj_t * ui_Ui5Label1;
extern lv_obj_t * ui_Ui5Panel2;
extern lv_obj_t * ui_Ui5Symbol2;
extern lv_obj_t * ui_Ui5Label2;
extern lv_obj_t * ui_Ui5Panel3;
extern lv_obj_t * ui_Ui5Symbol3;
extern lv_obj_t * ui_Ui5Label3;
extern lv_obj_t * ui_Ui5Panel4;
extern lv_obj_t * ui_Ui5Symbol4;
extern lv_obj_t * ui_Ui5Label4;
extern lv_obj_t * ui_Ui5Panel5;
extern lv_obj_t * ui_Ui5Symbol5;
extern lv_obj_t * ui_Ui5Label5;
// SCREEN: ui_UiPage6
void ui_UiPage6_screen_init(void);
extern lv_obj_t * ui_UiPage6;
extern lv_obj_t * ui_Ui6Panel1;
extern lv_obj_t * ui_Ui6Symbol1;
extern lv_obj_t * ui_Ui6Label1;
extern lv_obj_t * ui_Ui6Panel2;
extern lv_obj_t * ui_Ui6Symbol2;
extern lv_obj_t * ui_Ui6Label2;
extern lv_obj_t * ui_Ui6Panel3;
extern lv_obj_t * ui_Ui6Symbol3;
extern lv_obj_t * ui_Ui6Label3;
extern lv_obj_t * ui_Ui6Panel4;
extern lv_obj_t * ui_Ui6Symbol4;
extern lv_obj_t * ui_Ui6Label4;
extern lv_obj_t * ui_Ui6Panel5;
extern lv_obj_t * ui_Ui6Symbol5;
extern lv_obj_t * ui_Ui6Label5;
extern lv_obj_t * ui_Ui6Panel6;
extern lv_obj_t * ui_Ui6Symbol6;
extern lv_obj_t * ui_Ui6Label6;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_cold_symbol_png);    // assets\cold_symbol.png
LV_IMG_DECLARE(ui_img_switch_symbol_png);    // assets\switch_symbol.png
LV_IMG_DECLARE(ui_img_fan_symbol_png);    // assets\fan_symbol.png
LV_IMG_DECLARE(ui_img_kongtiao_bg_png);    // assets\kongtiao_bg.png
LV_IMG_DECLARE(ui_img_wifi_symbol_png);    // assets\wifi_symbol.png
LV_IMG_DECLARE(ui_img_display_symbol_png);    // assets\display_symbol.png
LV_IMG_DECLARE(ui_img_voice_symbol_png);    // assets\voice_symbol.png
LV_IMG_DECLARE(ui_img_info_symbol_png);    // assets\info_symbol.png
LV_IMG_DECLARE(ui_img_updata_symbol_png);    // assets\updata_symbol.png
LV_IMG_DECLARE(ui_img_first_page_png);    // assets\first_page.png
LV_IMG_DECLARE(ui_img_light_page_png);    // assets\light_page.png
LV_IMG_DECLARE(ui_img_air_page_png);    // assets\air_page.png
LV_IMG_DECLARE(ui_img_curtain_page_png);    // assets\curtain_page.png
LV_IMG_DECLARE(ui_img_mode_page_png);    // assets\mode_page.png
LV_IMG_DECLARE(ui_img_set_page_png);    // assets\set_page.png
LV_IMG_DECLARE(ui_img_anime_lin2_png);    // assets\anime_lin2.png
LV_IMG_DECLARE(ui_img_anime_line1_png);    // assets\anime_line1.png
LV_IMG_DECLARE(ui_img_arrow1_png);    // assets\arrow1.png
LV_IMG_DECLARE(ui_img_cloud1_png);    // assets\cloud1.png
LV_IMG_DECLARE(ui_img_common_switch1_png);    // assets\common_switch1.png

LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_FontHei24);
LV_FONT_DECLARE(ui_font_FontHei96);
LV_FONT_DECLARE(ui_font_FontHei32);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
